import { StyleSheet } from "react-native";
import { DS, SCREEN_TOP_PADDING } from "./constants";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: DS.bg },
  loading: { flex: 1, justifyContent: "center", alignItems: "center" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingTop: SCREEN_TOP_PADDING,
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: DS.border,
  },
  headerContent: { flex: 1, marginLeft: 14 },
  headerTitle: { fontFamily: "Montserrat-Bold", fontSize: 17, color: DS.textPrimary },
  headerSub: { fontFamily: "Montserrat-Regular", fontSize: 12, color: DS.accent },
  list: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 40 },
  card: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    backgroundColor: DS.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: DS.accent + "33",
    padding: 14,
    marginBottom: 10,
    position: "relative",
  },
  cardRead: { borderColor: DS.border, backgroundColor: DS.surface },
  unreadDot: {
    position: "absolute",
    top: 12,
    left: 8,
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: DS.accent,
  },
  iconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    flexShrink: 0,
  },
  content: { flex: 1 },
  titulo: { fontFamily: "Montserrat-Bold", fontSize: 13, color: DS.textPrimary, marginBottom: 3 },
  mensagem: { fontFamily: "Montserrat-Regular", fontSize: 13, color: DS.textPrimary, lineHeight: 19 },
  mensagemRead: { color: DS.textSecondary },
  time: { fontFamily: "Montserrat-Regular", fontSize: 11, color: DS.textMuted, marginTop: 4 },
  emptyWrap: { alignItems: "center", paddingTop: 60, gap: 12 },
  emptyText: { fontFamily: "Montserrat-SemiBold", fontSize: 14, color: DS.textMuted },
});
