import { StyleSheet } from "react-native";
import { DS } from "./constants";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: DS.bg,
  },
  scroll: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 52,
    paddingBottom: 12,
  },
  backBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  brandName: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 13,
    color: DS.accent,
    letterSpacing: 2,
  },
  confirmedBadge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: DS.success + "22",
    borderWidth: 1,
    borderColor: DS.success,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 6,
    gap: 6,
    marginBottom: 16,
  },
  confirmedBadgeText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 11,
    color: DS.success,
    letterSpacing: 1.5,
  },
  heroImage: {
    height: 200,
    backgroundColor: DS.bgSurface,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
    overflow: "hidden",
  },
  heroOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "rgba(0,0,0,0.6)",
    padding: 14,
  },
  heroTitle: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 14,
    color: DS.white,
  },
  showTitle: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 20,
    color: DS.white,
    marginBottom: 4,
    lineHeight: 28,
  },
  showSubtitle: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.textSec,
    marginBottom: 16,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 8,
  },
  infoText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 14,
    color: DS.white,
  },
  cacheCard: {
    backgroundColor: DS.bgCard,
    borderRadius: 12,
    padding: 16,
    marginTop: 12,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: DS.success + "44",
  },
  cacheLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 11,
    color: DS.textSec,
    letterSpacing: 2,
    marginBottom: 4,
  },
  cacheValue: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 22,
    color: DS.success,
  },
  sectionTitle: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 11,
    color: DS.white,
    letterSpacing: 2,
    marginBottom: 12,
    marginTop: 4,
  },
  locationCard: {
    backgroundColor: DS.bgCard,
    borderRadius: 12,
    padding: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  locationInfo: {
    flex: 1,
    marginRight: 10,
  },
  locationName: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 14,
    color: DS.white,
    marginBottom: 3,
  },
  locationAddr: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textSec,
  },
  mapsBtn: {
    backgroundColor: DS.accent + "22",
    borderWidth: 1,
    borderColor: DS.accent,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  mapsBtnText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 9,
    color: DS.accentLight,
    letterSpacing: 1,
  },
  mapVisual: {
    height: 100,
    backgroundColor: DS.bgCard,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
    gap: 4,
  },
  mapVisualText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textDis,
  },
  timelineCard: {
    backgroundColor: DS.bgCard,
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
  },
  timelineLine: {
    width: 2,
    height: 16,
    backgroundColor: DS.bgSurface,
    marginLeft: 9,
  },
  contactCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: DS.bgCard,
    borderRadius: 12,
    padding: 14,
    marginBottom: 20,
    gap: 12,
  },
  contactAvatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: DS.accent + "44",
    justifyContent: "center",
    alignItems: "center",
  },
  contactAvatarText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 18,
    color: DS.accent,
  },
  contactInfo: {
    flex: 1,
  },
  contactName: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 14,
    color: DS.white,
  },
  contactRole: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textSec,
  },
  contactActions: {
    flexDirection: "row",
    gap: 8,
  },
  contactActionBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: DS.bgSurface,
    justifyContent: "center",
    alignItems: "center",
  },
  btnReportar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: DS.danger,
    borderRadius: 12,
    paddingVertical: 14,
    gap: 10,
    marginBottom: 20,
  },
  btnReportarText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 13,
    color: DS.danger,
    letterSpacing: 1,
  },
});

export const loadingStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: DS.bg,
    justifyContent: "center",
    alignItems: "center",
  },
});

export const timelineItemStyles = StyleSheet.create({
  item: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    paddingVertical: 8,
  },
  textBlock: {
    flex: 1,
  },
  title: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 14,
    color: DS.white,
    marginBottom: 2,
  },
  subtitle: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textSec,
  },
});
