import { StyleSheet } from "react-native";
import { DS, SCREEN_TOP_PADDING } from "./constants";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: DS.bg },
  loadingContainer: {
    flex: 1,
    backgroundColor: DS.bg,
    justifyContent: "center",
    alignItems: "center",
  },
  scroll: { paddingBottom: 100 },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: SCREEN_TOP_PADDING,
    paddingBottom: 12,
  },
  backBtn: { flexDirection: "row", alignItems: "center", gap: 8 },
  backText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 14,
    color: DS.white,
  },
  headerIcons: { flexDirection: "row", alignItems: "center" },
  heroImage: {
    height: 220,
    backgroundColor: DS.bgSurface,
    justifyContent: "center",
    alignItems: "center",
  },
  heroBadgeRow: {
    position: "absolute",
    bottom: 12,
    left: 16,
    flexDirection: "row",
    gap: 8,
  },
  genreBadge: {
    backgroundColor: DS.accent,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  genreBadgeText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 10,
    color: DS.white,
    letterSpacing: 1,
  },
  liveBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: DS.danger + "CC",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    gap: 5,
  },
  liveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: DS.white,
  },
  liveBadgeText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 10,
    color: DS.white,
    letterSpacing: 1,
  },
  contentPad: { paddingHorizontal: 20, paddingTop: 20 },
  eventTitle: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 20,
    color: DS.white,
    marginBottom: 8,
    lineHeight: 28,
  },
  locationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 16,
  },
  locationText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.textSec,
  },
  cacheCard: {
    backgroundColor: DS.bgCard,
    borderRadius: 12,
    padding: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    borderWidth: 1,
    borderColor: DS.success + "44",
  },
  cacheLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 11,
    color: DS.textSec,
    letterSpacing: 2,
    marginBottom: 4,
  },
  cacheValue: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 18,
    color: DS.success,
  },
  infoGrid: { flexDirection: "row", gap: 12, marginBottom: 20 },
  infoGridCard: {
    flex: 1,
    backgroundColor: DS.bgCard,
    borderRadius: 12,
    padding: 14,
    alignItems: "center",
    gap: 6,
  },
  infoGridLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 10,
    color: DS.textSec,
    letterSpacing: 2,
  },
  infoGridValue: {
    fontFamily: "Montserrat-Bold",
    fontSize: 12,
    color: DS.white,
    textAlign: "center",
    lineHeight: 18,
  },
  sectionTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 15,
    color: DS.white,
    marginBottom: 12,
    marginTop: 8,
  },
  detailCard: {
    backgroundColor: DS.bgCard,
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
  },
  detailLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 14,
    color: DS.white,
  },
  toggleVisual: {
    width: 44,
    height: 24,
    borderRadius: 12,
    backgroundColor: DS.accent,
    justifyContent: "center",
    paddingHorizontal: 3,
    alignItems: "flex-end",
  },
  toggleThumb: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: DS.white,
  },
  separator: { height: 1, backgroundColor: DS.bgSurface, marginVertical: 4 },
  genrePillsRow: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginTop: 8 },
  genrePill: {
    backgroundColor: DS.bgSurface,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 10,
  },
  genrePillText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 11,
    color: DS.textSec,
    letterSpacing: 1,
  },
  descriptionText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: DS.textSec,
    lineHeight: 22,
    marginBottom: 20,
  },
  localCard: {
    backgroundColor: DS.bgCard,
    borderRadius: 12,
    padding: 14,
    marginBottom: 20,
    gap: 12,
  },
  localText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.textSec,
    lineHeight: 20,
  },
  localImagePlaceholder: {
    height: 100,
    backgroundColor: DS.bgSurface,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  reviewCard: {
    flexDirection: "row",
    backgroundColor: DS.bgCard,
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    gap: 12,
  },
  reviewAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: DS.bgSurface,
    justifyContent: "center",
    alignItems: "center",
  },
  reviewContent: { flex: 1, gap: 4 },
  reviewName: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 13,
    color: DS.white,
  },
  starsRow: { flexDirection: "row", gap: 3 },
  reviewText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textSec,
    lineHeight: 18,
  },
  fixedBottom: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: DS.bg,
    padding: 20,
    paddingBottom: 28,
    borderTopWidth: 1,
    borderTopColor: DS.bgSurface,
  },
  btnCandidatar: {
    backgroundColor: DS.accent,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: "center",
  },
  btnCandidatarText: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 12,
    color: DS.white,
    letterSpacing: 1.5,
  },
});
