import { StyleSheet } from "react-native";
import { DS } from "./constants";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: DS.bg,
    paddingTop: 50,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  headerTitle: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 17,
    color: DS.white,
  },
  headerSpacer: { width: 16 },
  tabRow: {
    flexDirection: "row",
    paddingHorizontal: 20,
    gap: 8,
    marginBottom: 16,
  },
  tab: {
    flex: 1,
    paddingVertical: 9,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: DS.textMuted,
    alignItems: "center",
  },
  tabText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 12,
    color: DS.textMuted,
  },
  listContent: {
    paddingHorizontal: 20,
    paddingBottom: 24,
    flexGrow: 1,
  },
  loading: {
    flex: 1,
    backgroundColor: DS.bg,
    justifyContent: "center",
    alignItems: "center",
  },
  emptyContainer: {
    alignItems: "center",
    paddingTop: 60,
    gap: 14,
  },
  emptyText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: DS.textSecondary,
    textAlign: "center",
  },

  card: {
    flexDirection: "row",
    backgroundColor: DS.card,
    borderRadius: 14,
    marginBottom: 12,
    overflow: "hidden",
  },
  thumbnail: {
    width: 72,
    backgroundColor: DS.surface,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
  },
  info: {
    flex: 1,
    padding: 12,
    gap: 4,
  },
  nameRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 4,
  },
  eventName: {
    flex: 1,
    fontFamily: "Montserrat-SemiBold",
    fontSize: 14,
    color: DS.white,
    marginRight: 8,
  },
  venueText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 12,
    color: DS.accentLight,
    marginBottom: 2,
  },
  dateText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textSecondary,
  },
  timeText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textMuted,
  },
  valueText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.textSecondary,
    marginTop: 2,
  },
  statusBadgePending: { marginTop: 6 },
  statusBadgePendingText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textSecondary,
    fontStyle: "italic",
  },
  statusBadgeAccepted: {
    backgroundColor: DS.success + "22",
    borderWidth: 1,
    borderColor: DS.success,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    alignSelf: "flex-start",
    marginTop: 6,
  },
  statusBadgeAcceptedText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 10,
    color: DS.success,
    letterSpacing: 1,
  },
  statusBadgeRejected: {
    backgroundColor: DS.danger + "22",
    borderWidth: 1,
    borderColor: DS.danger,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    alignSelf: "flex-start",
    marginTop: 6,
  },
  statusBadgeRejectedText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 10,
    color: DS.danger,
    letterSpacing: 1,
  },
  contractBtn: {
    marginTop: 8,
    backgroundColor: DS.accent,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
  },
  contractBtnText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 12,
    color: DS.white,
    letterSpacing: 1,
  },
});
