import { StyleSheet } from "react-native";
import { DS } from "./constants";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: DS.bg,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 16,
  },
  brandName: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 14,
    color: DS.accent,
    letterSpacing: 2,
  },
  avatarSmall: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: DS.bgCard,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: DS.accent,
  },
  scroll: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  title: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 26,
    color: DS.white,
    marginBottom: 12,
    lineHeight: 36,
  },
  titleAccent: {
    color: DS.accent,
  },
  subtitle: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: DS.textSec,
    lineHeight: 22,
    marginBottom: 24,
  },
  freePlanCard: {
    backgroundColor: DS.bgCard,
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
  },
  planTag: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 10,
    color: DS.textSec,
    letterSpacing: 2,
    marginBottom: 8,
  },
  freePrice: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 22,
    color: DS.white,
    marginBottom: 16,
  },
  separator: {
    height: 1,
    backgroundColor: DS.bgSurface,
    marginBottom: 14,
  },
  featureRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 10,
  },
  featureText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: DS.white,
  },
  featureTextDisabled: {
    color: DS.textDis,
    textDecorationLine: "line-through",
  },
  featureTextPro: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: DS.white,
  },
  btnContinueFree: {
    borderWidth: 1.5,
    borderColor: DS.textDis,
    borderRadius: 10,
    paddingVertical: 13,
    alignItems: "center",
    marginTop: 16,
  },
  btnContinueFreeText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 12,
    color: DS.textSec,
    letterSpacing: 1,
  },
  proPlanCard: {
    backgroundColor: DS.bgCard,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1.5,
    borderColor: DS.accent,
    marginBottom: 24,
  },
  proPlanHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  proPlanTag: {
    fontFamily: "Montserrat-Bold",
    fontSize: 10,
    color: DS.accentLight,
    letterSpacing: 2,
  },
  proDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: DS.accent,
    marginTop: 4,
  },
  recommendedBadge: {
    backgroundColor: DS.accent,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  recommendedText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 9,
    color: DS.white,
    letterSpacing: 1.5,
  },
  proPrice: {
    fontFamily: "Montserrat-Regular",
    fontSize: 16,
    color: DS.textSec,
    marginBottom: 16,
  },
  proPriceValue: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 26,
    color: DS.white,
  },
  proPriceMonth: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: DS.textSec,
  },
  btnAssinarPro: {
    backgroundColor: DS.accent,
    borderRadius: 10,
    paddingVertical: 15,
    alignItems: "center",
    marginTop: 16,
  },
  btnAssinarProText: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 12,
    color: DS.white,
    letterSpacing: 1.5,
  },
  trustRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 8,
  },
  trustItem: {
    flex: 1,
    alignItems: "center",
    gap: 6,
  },
  trustIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: DS.accent + "22",
    justifyContent: "center",
    alignItems: "center",
  },
  trustLabel: {
    fontFamily: "Montserrat-Regular",
    fontSize: 11,
    color: DS.textSec,
    textAlign: "center",
    lineHeight: 16,
  },
});
