import { StyleSheet } from "react-native";
import { DS } from "./constants";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: DS.bg },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 52,
    paddingHorizontal: 20,
    paddingBottom: 12,
  },
  closeBtn: { padding: 4 },
  headerBrand: {
    fontFamily: "Montserrat-Bold",
    fontSize: 14,
    color: DS.accent,
    letterSpacing: 2,
  },
  avatarSmall: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "rgba(167,139,250,0.15)",
    borderWidth: 1,
    borderColor: DS.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  scrollContent: { paddingHorizontal: 20, paddingBottom: 20 },
  showImagePlaceholder: {
    height: 160,
    backgroundColor: "#2D1B4E",
    borderRadius: 16,
    overflow: "hidden",
    marginBottom: 20,
  },
  showImageOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.55)",
    padding: 20,
    justifyContent: "flex-end",
  },
  howWasTitle: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 22,
    color: DS.white,
    marginBottom: 4,
  },
  showName: {
    fontFamily: "Montserrat-Bold",
    fontSize: 15,
    color: DS.accent,
    marginBottom: 2,
  },
  venueName: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.textSec,
  },
  ratingSection: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    padding: 16,
    marginBottom: 16,
  },
  ratingHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 14,
  },
  ratingTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 15,
    color: DS.white,
  },
  chipsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 14,
  },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  chipSelected: {
    backgroundColor: "rgba(167,139,250,0.15)",
    borderColor: DS.accent,
  },
  chipDangerSelected: {
    backgroundColor: "rgba(255,107,107,0.12)",
    borderColor: "rgba(255,107,107,0.4)",
  },
  chipText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 12,
    color: "#888",
  },
  chipTextSelected: { color: DS.accent },
  chipTextDanger: { color: DS.danger },
  commentSection: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    padding: 14,
    marginBottom: 16,
  },
  commentInput: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: DS.white,
    minHeight: 90,
    lineHeight: 22,
  },
  commentCounter: {
    fontFamily: "Montserrat-Regular",
    fontSize: 11,
    color: DS.textDis,
    textAlign: "right",
    marginTop: 8,
  },
  publishBtn: {
    backgroundColor: DS.accentBtn,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: "center",
    marginBottom: 12,
  },
  publishBtnText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 14,
    color: DS.white,
    letterSpacing: 1.5,
  },
  skipLink: { alignItems: "center", paddingVertical: 8 },
  skipLinkText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 13,
    color: DS.textDis,
    letterSpacing: 1,
  },
  scrollBottomSpacer: { height: 32 },
});
