import { StyleSheet } from "react-native";
import { COVER_HEIGHT, DS, PHOTO_SIZE, SCREEN_WIDTH } from "./constants";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: DS.bg },
  loading: { justifyContent: "center", alignItems: "center" },
  scroll: { paddingBottom: 40 },

  heroContainer: { width: SCREEN_WIDTH, height: COVER_HEIGHT, position: "relative" },
  heroImage: { width: SCREEN_WIDTH, height: COVER_HEIGHT },
  heroPlaceholder: { backgroundColor: DS.surface, justifyContent: "center", alignItems: "center" },
  heroGradient: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: COVER_HEIGHT / 2,
    backgroundColor: "rgba(9,9,15,0.65)",
  },
  heroActions: {
    position: "absolute",
    top: 52,
    left: 16,
    right: 16,
    flexDirection: "row",
    alignItems: "center",
  },
  heroActionsSpacer: { flex: 1 },
  iconBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "center",
    alignItems: "center",
  },

  section: { paddingHorizontal: 20, marginTop: 24 },
  nameRow: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 4 },
  name: { fontFamily: "AkiraExpanded-SuperBold", fontSize: 20, color: DS.textPrimary, flexShrink: 1 },
  dot: { width: 10, height: 10, borderRadius: 5, marginTop: 2 },
  dotGreen: { backgroundColor: DS.green },
  dotRed: { backgroundColor: "#EF4444" },
  tipoLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 12,
    color: DS.accent,
    letterSpacing: 1.5,
    marginBottom: 8,
  },
  row: { flexDirection: "row", alignItems: "center", gap: 6, marginBottom: 4 },
  locationText: { fontFamily: "Montserrat-Regular", fontSize: 12, color: DS.textSecondary, flex: 1 },

  statsRow: {
    flexDirection: "row",
    marginHorizontal: 20,
    marginTop: 20,
    backgroundColor: DS.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: DS.border,
    paddingVertical: 16,
  },
  statItem: { flex: 1, alignItems: "center" },
  statValue: { fontFamily: "Montserrat-Bold", fontSize: 22, color: DS.textPrimary },
  statValueHighlight: { color: DS.yellow },
  statLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 9,
    color: DS.textSecondary,
    letterSpacing: 1.2,
    marginTop: 4,
  },
  statDivider: { width: 1, backgroundColor: DS.border },

  sectionTitle: { fontFamily: "Montserrat-Bold", fontSize: 16, color: DS.textPrimary, marginBottom: 12 },
  bioText: { fontFamily: "Montserrat-Regular", fontSize: 13, color: DS.textSecondary, lineHeight: 20 },

  chipsWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
  },
  chipText: { fontFamily: "Montserrat-SemiBold", fontSize: 12 },

  photosGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  photoThumb: {
    width: PHOTO_SIZE,
    height: PHOTO_SIZE,
    borderRadius: 10,
    backgroundColor: DS.surface,
  },

  horariosCard: {
    backgroundColor: DS.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: DS.border,
    overflow: "hidden",
  },
  horarioRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 13,
  },
  horarioRowBorder: { borderTopWidth: 1, borderTopColor: DS.border },
  horarioDia: { fontFamily: "Montserrat-SemiBold", fontSize: 13, color: DS.textSecondary },
  horarioHora: { fontFamily: "Montserrat-Bold", fontSize: 13, color: DS.textPrimary },

  switchProfileBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: DS.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: DS.cyan + "40",
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  switchProfileText: {
    flex: 1,
    fontFamily: "Montserrat-SemiBold",
    fontSize: 14,
    color: DS.cyan,
  },
  signOutBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,107,107,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,107,107,0.3)",
    borderRadius: 12,
    paddingVertical: 15,
    marginTop: 14,
    marginBottom: 8,
  },
  signOutIcon: { marginRight: 10 },
  signOutText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 14,
    color: "#FF6B6B",
    letterSpacing: 1.5,
  },
});
