import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#09090F" },
  centered: {
    flex: 1,
    backgroundColor: "#09090F",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 32,
  },
  errorTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 18,
    color: "#FFFFFF",
    marginBottom: 8,
    textAlign: "center",
  },
  errorText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: "#8888AA",
    textAlign: "center",
    marginBottom: 24,
  },
  retryBtn: {
    backgroundColor: "#7B61FF",
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 24,
    marginBottom: 16,
  },
  retryBtnText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 13,
    color: "#FFFFFF",
    letterSpacing: 1,
  },
  backLink: { padding: 8 },
  backLinkText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 14,
    color: "#7B61FF",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 52,
    paddingHorizontal: 20,
    paddingBottom: 16,
  },
  backBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "rgba(123,97,255,0.12)",
    borderWidth: 1,
    borderColor: "#7B61FF",
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: { fontFamily: "Montserrat-Bold", fontSize: 18, color: "#FFFFFF" },
  headerSpacer: { width: 34 },
  scroll: { paddingHorizontal: 20, paddingBottom: 40 },
  label: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 11,
    color: "#8888AA",
    letterSpacing: 2,
    marginBottom: 8,
    marginTop: 20,
  },
  fieldLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 10,
    color: "#8888AA",
    letterSpacing: 2,
    marginBottom: 8,
    marginTop: 12,
  },
  sectionTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 14,
    color: "#FFFFFF",
    marginTop: 28,
    marginBottom: 12,
  },
  input: {
    backgroundColor: "#13101F",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#1E1A30",
    paddingHorizontal: 16,
    paddingVertical: 14,
    color: "#FFFFFF",
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
  },
  textArea: { minHeight: 100, textAlignVertical: "top", paddingTop: 12 },
  inputError: { borderColor: "#EF4444" },
  selector: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#13101F",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#1E1A30",
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  selectorDisabled: { opacity: 0.5 },
  selectorText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: "#FFFFFF",
    flex: 1,
  },
  selectorPlaceholder: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: "#555577",
    flex: 1,
  },
  row: { flexDirection: "row", gap: 10, marginTop: 4 },
  flex: { flex: 1 },
  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 4 },
  chipRowError: {
    borderWidth: 1,
    borderColor: "#EF4444",
    borderRadius: 10,
    padding: 8,
    marginTop: 4,
  },
  generosErrorWrap: {
    borderWidth: 1,
    borderColor: "#EF4444",
    borderRadius: 10,
    padding: 8,
  },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: "#1E1A30",
  },
  chipActive: { backgroundColor: "rgba(123,97,255,0.2)", borderColor: "#7B61FF" },
  chipText: { fontFamily: "Montserrat-SemiBold", fontSize: 12, color: "#8888AA" },
  chipTextActive: { color: "#7B61FF" },
  saveBtn: {
    backgroundColor: "#7B61FF",
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 32,
  },
  saveBtnDisabled: { opacity: 0.6 },
  saveBtnText: { fontFamily: "Montserrat-Bold", fontSize: 14, color: "#FFFFFF", letterSpacing: 1 },
  avatarSection: { alignItems: "center", marginTop: 8, marginBottom: 8 },
  avatarBtn: { position: "relative" },
  avatar: {
    width: 96,
    height: 96,
    borderRadius: 48,
    borderWidth: 3,
    borderColor: "#7B61FF",
  },
  avatarPlaceholder: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: "#13101F",
    borderWidth: 3,
    borderColor: "#7B61FF",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarBadge: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#7B61FF",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#09090F",
  },
  statsRow: {
    flexDirection: "row",
    backgroundColor: "#13101F",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#1E1A30",
    paddingVertical: 14,
    marginTop: 12,
  },
  statItem: { flex: 1, alignItems: "center", gap: 4 },
  statValue: {
    fontFamily: "Montserrat-Bold",
    fontSize: 16,
    color: "#FFFFFF",
  },
  statLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 8,
    color: "#8888AA",
    letterSpacing: 1,
    textAlign: "center",
    lineHeight: 12,
  },
  statDivider: {
    width: 1,
    backgroundColor: "#1E1A30",
    marginVertical: 4,
  },
  switchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "#13101F",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#1E1A30",
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginTop: 4,
  },
  switchLabel: {
    flex: 1,
    fontFamily: "Montserrat-SemiBold",
    fontSize: 14,
    color: "#FFFFFF",
  },
  switchHint: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: "#8888AA",
    marginTop: 2,
  },
  linkRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#13101F",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#1E1A30",
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 8,
    gap: 10,
  },
  linkText: {
    flex: 1,
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: "#8888AA",
  },
  addLinkBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    alignSelf: "flex-start",
    marginTop: 4,
    marginBottom: 8,
  },
  addLinkText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 13,
    color: "#7B61FF",
  },
  helper: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: "#555577",
    marginBottom: 10,
  },
});
