import { StyleSheet } from "react-native";
import { DS } from "./constants";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: DS.bg },
  centered: { alignItems: "center", justifyContent: "center" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 52,
    paddingHorizontal: 20,
    paddingBottom: 16,
  },
  backBtn: { padding: 4 },
  headerTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 13,
    color: DS.accent,
    letterSpacing: 1.5,
  },
  avatarSmall: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "rgba(167,139,250,0.15)",
    borderWidth: 1,
    borderColor: DS.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  scrollContent: { paddingHorizontal: 20, paddingBottom: 20 },
  confirmedRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  confirmedBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 8,
  },
  confirmedText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 11,
    letterSpacing: 1,
  },
  codeText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 13,
    color: DS.textDis,
  },
  showTitle: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 20,
    color: DS.accent,
    marginBottom: 4,
    lineHeight: 28,
  },
  artistName: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 14,
    color: DS.textSec,
    marginBottom: 16,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 8,
  },
  infoText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.white,
  },
  qrCard: {
    borderRadius: 20,
    overflow: "hidden",
    height: 320,
    marginTop: 20,
    marginBottom: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  qrCardOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.6)",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  qrInstruction: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 12,
    color: DS.textSec,
    textAlign: "center",
    marginTop: 16,
    marginBottom: 6,
  },
  qrCodeText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 11,
    color: DS.textDis,
    textAlign: "center",
    marginBottom: 12,
    letterSpacing: 0.5,
  },
  validBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
  },
  validDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
  },
  validText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 11,
    letterSpacing: 1,
  },
  supportLink: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  supportLinkText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textDis,
    textDecorationLine: "underline",
  },
  scrollBottomSpacer: { height: 32 },
});
