import { StyleSheet } from "react-native";
import { DS } from "./constants";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: DS.bg },
  center: { justifyContent: "center", alignItems: "center" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 52,
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: DS.border,
  },
  headerSpacer: { width: 18 },
  headerTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 17,
    color: DS.textPrimary,
  },
  scroll: { paddingHorizontal: 20, paddingTop: 28, paddingBottom: 40 },
  iconWrap: { alignItems: "center", marginBottom: 16 },
  iconCircle: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: `${DS.accent}22`,
    borderWidth: 2,
    borderColor: `${DS.accent}44`,
    justifyContent: "center",
    alignItems: "center",
  },
  statusBadge: {
    alignSelf: "center",
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 6,
    marginBottom: 8,
  },
  statusText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 11,
    letterSpacing: 1.5,
  },
  refText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textMuted,
    textAlign: "center",
    marginBottom: 24,
  },
  grid: { flexDirection: "row", gap: 10 },
  infoCard: {
    backgroundColor: DS.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: DS.border,
    padding: 14,
    marginBottom: 10,
    gap: 4,
  },
  infoCardFlex: { flex: 1 },
  infoLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 10,
    color: DS.textMuted,
    letterSpacing: 1.5,
  },
  infoValue: {
    fontFamily: "Montserrat-Bold",
    fontSize: 15,
    color: DS.textPrimary,
  },
  infoValueSm: {
    fontFamily: "Montserrat-Bold",
    fontSize: 13,
    color: DS.textPrimary,
  },
  infoValueSuccess: { color: DS.success },
  infoValueAmber: { color: DS.amber },
  artistRow: { flexDirection: "row", alignItems: "center", gap: 10, marginTop: 4 },
  artistAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: DS.surface,
    justifyContent: "center",
    alignItems: "center",
  },
  pendingBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: `${DS.amber}18`,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: `${DS.amber}44`,
    padding: 12,
    marginBottom: 12,
  },
  pendingBannerText: {
    flex: 1,
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textSecondary,
    lineHeight: 18,
  },
  clauseCard: {
    flexDirection: "row",
    gap: 12,
    alignItems: "flex-start",
    backgroundColor: `${DS.danger}11`,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: `${DS.danger}33`,
    padding: 14,
    marginTop: 8,
    marginBottom: 24,
  },
  clauseTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 11,
    color: DS.danger,
    letterSpacing: 1.5,
    marginBottom: 4,
  },
  clauseText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textSecondary,
    lineHeight: 18,
  },
  btnRate: {
    backgroundColor: DS.accent,
    borderRadius: 12,
    paddingVertical: 16,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
  },
  btnRateText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 13,
    color: "#fff",
    letterSpacing: 0.5,
  },
  btnComplete: {
    backgroundColor: DS.success,
    borderRadius: 12,
    paddingVertical: 16,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
  },
  btnCompleteText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 13,
    color: "#fff",
    letterSpacing: 0.5,
  },
  btnCancel: {
    borderWidth: 1.5,
    borderColor: DS.danger,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    marginBottom: 12,
  },
  btnCancelText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 13,
    color: DS.danger,
  },
  disabled: { opacity: 0.5 },
});
