import { StyleSheet } from "react-native";
import { DS } from "./constants";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: DS.bg },
  centered: { alignItems: "center", justifyContent: "center" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 52,
    paddingHorizontal: 20,
    paddingBottom: 16,
  },
  backBtn: { padding: 4 },
  headerTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 17,
    color: DS.white,
  },
  scrollContent: { padding: 20, gap: 16 },
  showCard: {
    flexDirection: "row",
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    overflow: "hidden",
  },
  showCardImage: {
    width: 80,
    backgroundColor: DS.showImageBg,
    alignItems: "center",
    justifyContent: "center",
  },
  showCardInfo: { flex: 1, padding: 12 },
  genreBadge: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(167,139,250,0.15)",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 5,
    marginBottom: 4,
  },
  genreBadgeText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 9,
    color: DS.accent,
    letterSpacing: 1,
  },
  showTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 14,
    color: DS.white,
    marginBottom: 4,
  },
  showMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginBottom: 3,
  },
  showMetaText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 11,
    color: DS.textSec,
  },
  sectionCard: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    padding: 16,
  },
  sectionTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 15,
    color: DS.white,
    marginBottom: 4,
  },
  sectionSubtitle: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textDis,
    marginBottom: 16,
  },
  ticketRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 10,
  },
  ticketType: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 14,
    color: DS.white,
    marginBottom: 2,
  },
  ticketPrice: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.textSec,
  },
  qtyControl: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  qtyBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(167,139,250,0.4)",
    alignItems: "center",
    justifyContent: "center",
  },
  qtyValue: {
    fontFamily: "Montserrat-Bold",
    fontSize: 16,
    color: DS.white,
    minWidth: 20,
    textAlign: "center",
  },
  divider: {
    height: 1,
    backgroundColor: "rgba(255,255,255,0.06)",
    marginVertical: 8,
  },
  inputWrapper: { marginBottom: 12 },
  inputLabel: {
    fontFamily: "Montserrat-Bold",
    fontSize: 10,
    color: DS.accent,
    letterSpacing: 1.5,
    marginBottom: 6,
  },
  input: {
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: DS.white,
  },
  inputError: {
    borderColor: DS.danger,
  },
  cardRow: { flexDirection: "row" },
  cardFieldSpacer: { width: 12 },
  payTabs: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 16,
    marginTop: 8,
  },
  payTab: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "rgba(255,255,255,0.03)",
  },
  payTabActive: {
    borderColor: DS.accent,
    backgroundColor: "rgba(167,139,250,0.1)",
  },
  payTabText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 13,
    color: DS.textDis,
  },
  payTabTextActive: { color: DS.accent },
  pixInfo: {
    alignItems: "center",
    paddingVertical: 20,
  },
  pixText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.textSec,
    textAlign: "center",
    lineHeight: 20,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  summaryLabel: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.textSec,
  },
  summaryValue: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 13,
    color: DS.white,
  },
  totalLabel: {
    fontFamily: "Montserrat-Bold",
    fontSize: 16,
    color: DS.white,
  },
  totalValue: {
    fontFamily: "Montserrat-Bold",
    fontSize: 20,
    color: DS.accent,
  },
  scrollBottomSpacer: { height: 100 },
  stickyBottom: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: DS.bgBottom,
    borderTopWidth: 1,
    borderTopColor: DS.bgSurface,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 28,
  },
  finishBtn: {
    backgroundColor: DS.accentBtn,
    borderRadius: 12,
    paddingVertical: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  finishBtnDisabled: { opacity: 0.4 },
  finishBtnText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 14,
    color: DS.white,
    letterSpacing: 1.5,
  },
  finishBtnIcon: { marginRight: 8 },
});
