import { StyleSheet } from "react-native";
import { DS, SCREEN_TOP_PADDING } from "./constants";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: DS.bg },
  loadingContainer: {
    flex: 1,
    backgroundColor: DS.bg,
    justifyContent: "center",
    alignItems: "center",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: SCREEN_TOP_PADDING,
    paddingBottom: 16,
  },
  brandName: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 14,
    color: DS.accent,
    letterSpacing: 2,
  },
  scroll: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 40 },
  docIconContainer: { alignItems: "center", marginBottom: 16 },
  docIconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: DS.accent + "22",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: DS.accent + "44",
  },
  contractTitle: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 20,
    color: DS.white,
    textAlign: "center",
    marginBottom: 6,
  },
  contractRef: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.textDis,
    textAlign: "center",
    marginBottom: 16,
  },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: DS.success + "22",
    borderWidth: 1,
    borderColor: DS.success,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 6,
    gap: 6,
    marginBottom: 16,
  },
  statusBadgeText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 11,
    color: DS.success,
    letterSpacing: 1.5,
  },
  waitBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    backgroundColor: DS.amber + "18",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: DS.amber + "44",
    padding: 14,
    marginBottom: 16,
  },
  waitBannerText: {
    flex: 1,
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textSec,
    lineHeight: 18,
  },
  rejectBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    backgroundColor: DS.danger + "18",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: DS.danger + "44",
    padding: 14,
    marginBottom: 16,
  },
  rejectBannerText: {
    flex: 1,
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textSec,
    lineHeight: 18,
  },
  infoCard: {
    backgroundColor: DS.bgCard,
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    gap: 4,
  },
  gridRow: { flexDirection: "row", gap: 10 },
  infoCardLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 10,
    color: DS.textDis,
    letterSpacing: 2,
  },
  infoCardValue: { fontFamily: "Montserrat-Bold", fontSize: 16, color: DS.white },
  infoCardValueSmall: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 13,
    color: DS.white,
    lineHeight: 18,
  },
  sectionTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 13,
    color: DS.textSec,
    letterSpacing: 2,
    marginTop: 20,
    marginBottom: 10,
  },
  workflowHint: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textSec,
    marginBottom: 8,
  },
  termsCard: { backgroundColor: DS.bgCard, borderRadius: 12, padding: 16, marginBottom: 16 },
  termRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 6,
  },
  termLabel: { fontFamily: "Montserrat-SemiBold", fontSize: 14, color: DS.white },
  termNote: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textSec,
    flex: 1,
    textAlign: "right",
  },
  termValue: { fontFamily: "Montserrat-Bold", fontSize: 16, color: DS.success },
  termDivider: { height: 1, backgroundColor: "#1A1040", marginVertical: 8 },
  legalText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 11,
    color: DS.textDis,
    textAlign: "center",
    lineHeight: 17,
    paddingHorizontal: 10,
    marginTop: 16,
  },
});
