import { StyleSheet } from "react-native";
import { DS } from "./constants";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: DS.bg,
  },
  closeBtn: {
    position: "absolute",
    top: 52,
    left: 20,
    zIndex: 10,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: DS.bgCard,
    justifyContent: "center",
    alignItems: "center",
  },
  scroll: {
    paddingHorizontal: 24,
    paddingTop: 110,
    paddingBottom: 40,
  },
  title: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 20,
    color: DS.white,
    textAlign: "center",
    lineHeight: 30,
    marginBottom: 28,
  },
  titleAccent: {
    color: DS.accent,
  },
  starsRow: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 14,
    marginBottom: 16,
  },
  ratingLabel: {
    fontFamily: "Montserrat-Bold",
    fontSize: 13,
    color: DS.gold,
    textAlign: "center",
    letterSpacing: 2,
    marginBottom: 24,
  },
  sectionTitle: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 13,
    color: DS.textSec,
    letterSpacing: 1.5,
    marginBottom: 12,
    marginTop: 8,
  },
  chipsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 20,
  },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: DS.textDis,
    backgroundColor: DS.bgCard,
  },
  chipText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 12,
    color: DS.textDis,
  },
  input: {
    backgroundColor: DS.bgInput,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    color: DS.white,
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    minHeight: 110,
    borderWidth: 1,
    borderColor: DS.bgSurface,
    marginBottom: 24,
  },
  btnEnviar: {
    backgroundColor: DS.accent,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: "center",
    marginBottom: 12,
  },
  btnEnviarText: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 12,
    color: DS.white,
    letterSpacing: 1.5,
  },
  btnPular: {
    alignItems: "center",
    paddingVertical: 12,
  },
  btnPularText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 14,
    color: DS.textDis,
    letterSpacing: 2,
  },
  disabled: { opacity: 0.7 },
});
