import { StyleSheet } from "react-native";
import { DS } from "./constants";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: DS.bg },
  bgTexture: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    opacity: 0.06,
  },
  glow: {
    position: "absolute",
    top: -100,
    alignSelf: "center",
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: DS.accent,
    opacity: 0.15,
  },
  kav: { flex: 1 },
  scroll: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 80,
    paddingBottom: 40,
    justifyContent: "center",
  },
  iconWrap: { alignItems: "center", marginBottom: 32 },
  iconCircle: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "rgba(123,97,255,0.15)",
    borderWidth: 1,
    borderColor: "rgba(123,97,255,0.3)",
    justifyContent: "center",
    alignItems: "center",
  },
  heading: {
    fontFamily: "Montserrat-Bold",
    fontSize: 26,
    color: DS.white,
    marginBottom: 8,
  },
  headingSub: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: DS.textMuted,
    lineHeight: 22,
    marginBottom: 32,
  },
  fieldWrap: { marginBottom: 20 },
  label: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 11,
    color: DS.textMuted,
    letterSpacing: 1.5,
    marginBottom: 8,
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: DS.inputBg,
    borderWidth: 1,
    borderColor: DS.inputBorder,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 10,
  },
  input: {
    flex: 1,
    fontFamily: "Montserrat-Regular",
    fontSize: 15,
    color: DS.white,
    padding: 0,
  },
  inputError: { borderColor: DS.error },
  errorText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.error,
    marginTop: 6,
    marginLeft: 4,
  },
  btn: {
    backgroundColor: DS.accent,
    borderRadius: 14,
    paddingVertical: 17,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 8,
  },
  btnDisabled: { opacity: 0.6 },
  btnText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 15,
    color: DS.white,
    letterSpacing: 1.5,
  },
  successWrap: { alignItems: "center", paddingTop: 20 },
  successIcon: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: "rgba(34,197,94,0.15)",
    borderWidth: 1,
    borderColor: "rgba(34,197,94,0.3)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 28,
  },
});
