import { StyleSheet } from "react-native";
import { DS } from "./constants";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: DS.bg },
  progressRow: {
    flexDirection: "row",
    paddingHorizontal: 20,
    gap: 6,
    marginBottom: 24,
  },
  progressSegment: { flex: 1, height: 3, borderRadius: 2 },
  progressActive: { backgroundColor: DS.accent },
  scrollContent: { paddingHorizontal: 20, paddingBottom: 20 },
  titleBlock: { marginBottom: 8 },
  titleWhite: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 26,
    color: DS.white,
    lineHeight: 34,
  },
  titleAccent: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 26,
    color: DS.accentGreen,
    lineHeight: 34,
    marginBottom: 12,
  },
  subtitle: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: DS.textMuted,
    marginBottom: 20,
  },
  searchBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.06)",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 16,
    marginBottom: 4,
    height: 52,
  },
  searchBoxError: {
    borderColor: "#EF4444",
  },
  searchIcon: { marginRight: 12 },
  searchInput: {
    flex: 1,
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: DS.white,
  },
  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  toggleLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 13,
    color: DS.white,
  },
  radiusCard: {
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(167,139,250,0.2)",
    padding: 16,
    marginBottom: 24,
  },
  radiusCardTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 11,
    color: DS.accent,
    letterSpacing: 2,
    marginBottom: 8,
  },
  radiusValue: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 32,
    color: DS.white,
    marginBottom: 16,
  },
  sliderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 16,
  },
  sliderLabel: {
    fontFamily: "Montserrat-Regular",
    fontSize: 10,
    color: DS.textDis,
    width: 52,
    lineHeight: 14,
  },
  sliderTrack: {
    flex: 1,
    height: 4,
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 2,
    flexDirection: "row",
    alignItems: "center",
    position: "relative",
  },
  sliderFill: {
    height: 4,
    backgroundColor: DS.accent,
    borderRadius: 2,
  },
  sliderThumb: {
    position: "absolute",
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: DS.accent,
    right: -7,
  },
  radiusControls: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
  },
  radiusBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: DS.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  radiusBtnLabel: {
    fontFamily: "Montserrat-Bold",
    fontSize: 16,
    color: DS.white,
    minWidth: 60,
    textAlign: "center",
  },
  sectionHeader: { marginBottom: 16 },
  sectionTitleWhite: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 20,
    color: DS.white,
  },
  sectionTitleAccent: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 20,
    color: DS.accent,
  },
  venueGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  venueChip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  venueChipSelected: {
    backgroundColor: "rgba(167,139,250,0.15)",
    borderColor: DS.accent,
  },
  venueChipText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 13,
    color: DS.textChip,
  },
  venueChipTextSelected: { color: DS.accent },
  footer: {
    paddingHorizontal: 20,
    paddingBottom: 32,
    paddingTop: 12,
    backgroundColor: DS.bg,
  },
  startBtn: {
    backgroundColor: DS.primary,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: "center",
  },
  startBtnText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 14,
    color: DS.white,
    letterSpacing: 1.5,
  },
});

export const headerStyles = StyleSheet.create({
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 52,
    paddingHorizontal: 20,
    paddingBottom: 12,
  },
  headerLeft: { width: 60 },
  headerBrand: {
    fontFamily: "Montserrat-Bold",
    fontSize: 13,
    color: DS.accent,
    letterSpacing: 2,
  },
  skipBtn: { width: 60, alignItems: "flex-end" },
  skipText: { fontFamily: "Montserrat-SemiBold", fontSize: 12, color: DS.accent },
});
