import { StyleSheet } from "react-native";
import { DS, SCREEN_TOP_PADDING } from "./constants";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: DS.bg },
  loadingContainer: {
    flex: 1,
    backgroundColor: DS.bg,
    justifyContent: "center",
    alignItems: "center",
  },
  scroll: {
    paddingHorizontal: 20,
    paddingTop: SCREEN_TOP_PADDING,
    paddingBottom: 20,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 24,
  },
  avatarSmall: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: DS.bgCard,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: DS.accent,
  },
  brandName: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 14,
    color: DS.accent,
    letterSpacing: 2,
  },
  greetingBlock: { marginBottom: 24 },
  greetingText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 15,
    color: DS.textSec,
  },
  greetingName: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 22,
    color: DS.accent,
    marginTop: 2,
  },
  greetingSub: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.textDis,
    marginTop: 4,
  },
  metricsRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 24,
  },
  metricCard: {
    flex: 1,
    backgroundColor: DS.bgCard,
    borderRadius: 14,
    padding: 16,
    borderLeftWidth: 3,
    gap: 6,
  },
  metricValue: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 26,
    color: DS.white,
    marginTop: 8,
  },
  metricLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 10,
    color: DS.textSec,
    letterSpacing: 1,
    lineHeight: 15,
  },
  analyticsSmallRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 24,
  },
  analyticsSmallCard: {
    backgroundColor: DS.bgCard,
    borderRadius: 14,
    padding: 14,
  },
  analyticsSmallTitle: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 10,
    color: DS.textSec,
    letterSpacing: 1.5,
    lineHeight: 15,
    marginBottom: 8,
  },
  analyticsSmallValue: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 22,
    color: DS.white,
    marginBottom: 4,
  },
  analyticsSmallSub: {
    fontFamily: "Montserrat-Regular",
    fontSize: 11,
    color: DS.textDis,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  sectionTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 16,
    color: DS.white,
  },
  sectionLink: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 12,
    color: DS.accentLight,
  },
  sectionSub: {
    fontFamily: "Montserrat-Regular",
    fontSize: 11,
    color: DS.textDis,
  },
  emptyShowsText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.textSec,
    marginBottom: 20,
  },
  showCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: DS.bgCard,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: DS.bgSurface,
    borderLeftWidth: 4,
    padding: 14,
    marginBottom: 10,
    gap: 12,
  },
  showCardBody: { flex: 1 },
  dateBadge: {
    width: 48,
    height: 52,
    backgroundColor: DS.bgSurface,
    borderRadius: 12,
    borderWidth: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  dateDay: {
    fontFamily: "Montserrat-Bold",
    fontSize: 18,
    color: DS.white,
    lineHeight: 20,
  },
  dateMes: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 10,
    marginTop: 2,
  },
  showTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 15,
    color: DS.white,
  },
  showSub: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textSec,
    marginTop: 3,
  },
  confirmedBadge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 5,
    marginTop: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    backgroundColor: "rgba(16,185,129,0.12)",
    borderWidth: 1,
    borderColor: "rgba(16,185,129,0.25)",
  },
  confirmedBadgeText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 10,
    color: DS.success,
  },
  emptyCard: {
    backgroundColor: DS.bgCard,
    borderRadius: 14,
    padding: 28,
    alignItems: "center",
    gap: 12,
  },
  emptyText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: DS.textSec,
  },
  emptyBtn: {
    backgroundColor: DS.accent,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
  },
  emptyBtnText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 13,
    color: DS.white,
  },
  contractCard: {
    flexDirection: "row",
    backgroundColor: DS.bgCard,
    borderRadius: 14,
    marginBottom: 12,
    overflow: "hidden",
  },
  contractImagePlaceholder: {
    width: 80,
    backgroundColor: DS.bgSurface,
    justifyContent: "center",
    alignItems: "center",
  },
  contractInfo: { flex: 1, padding: 12 },
  contractBadgeRow: { flexDirection: "row", marginBottom: 6 },
  contractBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6 },
  contractBadgeText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 9,
    letterSpacing: 1,
  },
  contractEventName: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 14,
    color: DS.white,
    marginBottom: 4,
  },
  contractLocationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 3,
  },
  contractLocationText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 11,
    color: DS.textDis,
  },
  contractDateText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 11,
    color: DS.textSec,
    marginBottom: 3,
  },
  contractCacheText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 13,
    color: DS.success,
  },
  contractFab: {
    width: 36,
    alignSelf: "stretch",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: DS.accent,
    margin: 12,
    borderRadius: 8,
  },
});
