import { StyleSheet } from "react-native";
import { DS } from "./constants";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: DS.bg },
  loadingContainer: {
    flex: 1,
    backgroundColor: DS.bg,
    alignItems: "center",
    justifyContent: "center",
  },
  coverImage: {
    height: 280,
    justifyContent: "space-between",
    overflow: "hidden",
  },
  coverBackgroundImage: {
    ...StyleSheet.absoluteFillObject,
  },
  coverOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  topActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingTop: 52,
    paddingHorizontal: 20,
  },
  actionBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(0,0,0,0.5)",
    alignItems: "center",
    justifyContent: "center",
  },
  coverInfo: {
    padding: 20,
  },
  genreBadge: {
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    marginBottom: 8,
  },
  genreBadgeText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 10,
    letterSpacing: 1,
  },
  coverTitle: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 26,
    color: DS.white,
  },
  scroll: { flex: 1 },
  scrollContent: { padding: 20 },
  infoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 24,
  },
  infoItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    width: "46%",
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    padding: 12,
  },
  infoLabel: {
    fontFamily: "Montserrat-Regular",
    fontSize: 11,
    color: DS.textDis,
    marginBottom: 2,
  },
  infoValue: {
    fontFamily: "Montserrat-Bold",
    fontSize: 13,
    color: DS.white,
  },
  section: { marginBottom: 24 },
  sectionTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 16,
    color: DS.white,
    marginBottom: 12,
  },
  aboutText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: DS.textSec,
    lineHeight: 22,
  },
  ratingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  ratingValue: {
    fontFamily: "Montserrat-Bold",
    fontSize: 18,
    color: DS.white,
  },
  ratingCount: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.textSec,
  },
  attendeesRow: { flexDirection: "row", alignItems: "center" },
  attendeeAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: DS.bg,
  },
  attendeesMore: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textSec,
    marginLeft: 12,
  },
  artistCard: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  artistAvatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "rgba(167,139,250,0.15)",
    borderWidth: 1,
    borderColor: DS.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  artistAvatarMuted: {
    borderColor: DS.textDis,
  },
  artistInfo: { flex: 1 },
  artistName: {
    fontFamily: "Montserrat-Bold",
    fontSize: 15,
    color: DS.white,
    marginBottom: 4,
  },
  artistNameMuted: {
    color: DS.textDis,
  },
  artistBio: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textSec,
  },
  viewProfileBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  viewProfileText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 11,
    color: DS.accent,
  },
  venueCard: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    padding: 14,
  },
  venueName: {
    fontFamily: "Montserrat-Bold",
    fontSize: 15,
    color: DS.white,
    marginBottom: 6,
  },
  venueAddress: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 12,
  },
  venueAddressText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.textSec,
    flex: 1,
  },
  commentsLink: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    marginBottom: 8,
  },
  commentsLinkText: {
    flex: 1,
    fontFamily: "Montserrat-SemiBold",
    fontSize: 14,
    color: DS.white,
  },
  scrollBottomSpacer: { height: 100 },
  stickyBottom: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: DS.bgBottom,
    borderTopWidth: 1,
    borderTopColor: DS.bgSurface,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 28,
    gap: 16,
  },
  priceRow: {},
  priceLabel: {
    fontFamily: "Montserrat-Regular",
    fontSize: 11,
    color: "#888",
  },
  priceValue: {
    fontFamily: "Montserrat-Bold",
    fontSize: 18,
    color: DS.price,
  },
  buyBtn: {
    flex: 1,
    backgroundColor: DS.accentBtn,
    borderRadius: 12,
    paddingVertical: 15,
    alignItems: "center",
  },
  confirmBtn: {
    flex: 1,
    borderWidth: 1.5,
    borderColor: DS.accent,
    borderRadius: 12,
    paddingVertical: 15,
    alignItems: "center",
  },
  disabledBtn: {
    flex: 1,
    backgroundColor: DS.disabledBtn,
    borderRadius: 12,
    paddingVertical: 15,
    alignItems: "center",
  },
  buyBtnText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 13,
    color: DS.white,
    letterSpacing: 1,
  },
});
