import { StyleSheet } from "react-native";
import { DS } from "./constants";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: DS.bg },
  loading: { justifyContent: "center", alignItems: "center" },
  scroll: { paddingTop: 52, paddingHorizontal: 20, paddingBottom: 24 },

  header: { flexDirection: "row", alignItems: "center", marginBottom: 20 },
  avatarSmall: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: DS.card,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 8,
  },
  headerName: { flex: 1, fontFamily: "Montserrat-SemiBold", fontSize: 15, color: DS.accent },

  greeting: { fontFamily: "Montserrat-Bold", fontSize: 26, color: DS.textPrimary, marginBottom: 4 },
  greetingSub: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.textSecondary,
    marginBottom: 24,
  },

  metricsGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12, marginBottom: 20 },
  metricCard: {
    flex: 1,
    minWidth: "45%",
    backgroundColor: DS.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: DS.border,
    padding: 16,
  },
  metricLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 10,
    color: DS.textSecondary,
    letterSpacing: 1.5,
    marginBottom: 8,
  },
  metricValue: { fontFamily: "Montserrat-Bold", fontSize: 28 },

  publishBtn: {
    backgroundColor: DS.accent,
    borderRadius: 12,
    paddingVertical: 14,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 28,
  },
  publishBtnIcon: { marginRight: 8 },
  publishBtnText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 13,
    color: DS.textPrimary,
    letterSpacing: 1,
  },

  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  sectionTitle: { fontFamily: "Montserrat-Bold", fontSize: 17, color: DS.textPrimary },
  sectionLink: { fontFamily: "Montserrat-SemiBold", fontSize: 12, color: DS.accent },

  showCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: DS.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: DS.border,
    borderLeftWidth: 4,
    padding: 14,
    marginBottom: 10,
    gap: 12,
  },
  showCardBody: { flex: 1 },
  dateBadge: {
    width: 48,
    height: 52,
    backgroundColor: DS.surface,
    borderRadius: 12,
    borderWidth: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  dateDay: { fontFamily: "Montserrat-Bold", fontSize: 18, color: DS.textPrimary, lineHeight: 20 },
  dateMes: { fontFamily: "Montserrat-SemiBold", fontSize: 10, marginTop: 2 },
  showTitle: { fontFamily: "Montserrat-Bold", fontSize: 15, color: DS.textPrimary },
  showSub: { fontFamily: "Montserrat-Regular", fontSize: 12, color: DS.textSecondary, marginTop: 3 },
  confirmedBadge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 5,
    marginTop: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    backgroundColor: "rgba(0,200,83,0.12)",
    borderWidth: 1,
    borderColor: "rgba(0,200,83,0.25)",
  },
  confirmedBadgeText: { fontFamily: "Montserrat-SemiBold", fontSize: 10, color: DS.success },
  genreRow: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginTop: 8 },
  genreBadge: { borderWidth: 1, borderRadius: 10, paddingHorizontal: 8, paddingVertical: 3 },
  genreBadgeText: { fontFamily: "Montserrat-Bold", fontSize: 9, letterSpacing: 0.5 },
  emptyText: { fontFamily: "Montserrat-Regular", fontSize: 13, color: DS.textSecondary, marginBottom: 16 },
});
