import { StyleSheet } from "react-native";
import { COVER_HEIGHT, DS } from "./constants";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: DS.bg },
  loading: {
    flex: 1,
    backgroundColor: DS.bg,
    alignItems: "center",
    justifyContent: "center",
  },
  errorContainer: {
    flex: 1,
    backgroundColor: DS.bg,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  errorText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 16,
    color: DS.textSecondary,
    marginBottom: 20,
    textAlign: "center",
  },
  errorBackBtn: {
    backgroundColor: DS.accentSolid,
    borderRadius: 10,
    paddingHorizontal: 24,
    paddingVertical: 12,
  },
  errorBackBtnText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 13,
    color: DS.textPrimary,
    letterSpacing: 1,
  },
  headerImage: {
    height: COVER_HEIGHT,
    position: "relative",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  coverImage: {
    ...StyleSheet.absoluteFillObject,
    resizeMode: "cover",
  },
  headerOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.45)",
  },
  backBtn: {
    position: "absolute",
    top: 52,
    left: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(0,0,0,0.5)",
    alignItems: "center",
    justifyContent: "center",
  },
  favoriteHeaderBtn: {
    position: "absolute",
    top: 52,
    right: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(0,0,0,0.5)",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarContainer: {
    position: "absolute",
    bottom: -44,
    alignSelf: "center",
  },
  avatar: {
    width: 88,
    height: 88,
    borderRadius: 44,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: DS.bg,
  },
  scroll: { flex: 1 },
  scrollContent: { paddingTop: 56, paddingHorizontal: 20 },
  typeBadge: {
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 6,
    marginBottom: 8,
  },
  typeBadgeText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 10,
    letterSpacing: 1,
  },
  name: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 22,
    color: DS.textPrimary,
    marginBottom: 6,
    lineHeight: 30,
  },
  rating: {
    fontFamily: "Montserrat-Bold",
    fontSize: 14,
    color: DS.gold,
    marginBottom: 8,
  },
  locationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 20,
  },
  locationText: {
    flex: 1,
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.textSecondary,
  },
  infoGrid: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 24,
  },
  infoCard: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    padding: 12,
    gap: 6,
  },
  infoLabel: {
    fontFamily: "Montserrat-Bold",
    fontSize: 9,
    color: DS.textMuted,
    letterSpacing: 1,
  },
  infoValue: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 12,
    color: DS.textPrimary,
  },
  section: { marginBottom: 24 },
  sectionTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 16,
    color: DS.textPrimary,
    marginBottom: 12,
  },
  photosRow: { gap: 10 },
  photoThumb: {
    width: 110,
    height: 110,
    borderRadius: 10,
    backgroundColor: DS.surface,
  },
  description: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: DS.textSecondary,
    lineHeight: 22,
  },
  genreRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  genreChip: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  genreChipText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 10,
    letterSpacing: 0.5,
  },
  emptySection: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.textMuted,
  },
  showRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.05)",
  },
  showDateBlock: { width: 44, alignItems: "center" },
  showDate: {
    fontFamily: "Montserrat-Bold",
    fontSize: 12,
    color: DS.accent,
    textAlign: "center",
  },
  showInfo: { flex: 1 },
  showTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 13,
    color: DS.textPrimary,
    marginBottom: 2,
  },
  showArtist: {
    fontFamily: "Montserrat-Regular",
    fontSize: 11,
    color: DS.textSecondary,
  },
  scrollBottomSpacer: { height: 100 },
  stickyBottom: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#0D0D14",
    borderTopWidth: 1,
    borderTopColor: DS.border,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 28,
  },
  backBottomBtn: {
    backgroundColor: DS.accentSolid,
    borderRadius: 12,
    paddingVertical: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  backBottomBtnIcon: { marginRight: 8 },
  backBottomBtnText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 14,
    color: DS.textPrimary,
    letterSpacing: 1,
  },
});
