import { StyleSheet } from "react-native";
import { DS, SCREEN_TOP_PADDING } from "./constants";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: DS.bg,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: SCREEN_TOP_PADDING,
    paddingBottom: 16,
  },
  backBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  headerTitle: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 16,
    color: DS.white,
  },
  scroll: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  cardSectionTitle: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 11,
    color: DS.textSec,
    letterSpacing: 2.5,
    marginBottom: 10,
    marginTop: 20,
  },
  summaryCard: {
    backgroundColor: DS.bgCard,
    borderRadius: 14,
    padding: 16,
    gap: 10,
  },
  summaryEventName: {
    fontFamily: "Montserrat-Bold",
    fontSize: 17,
    color: DS.white,
    marginBottom: 4,
  },
  summaryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  summaryText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: DS.textSec,
  },
  messageInput: {
    backgroundColor: DS.bgInput,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    color: DS.white,
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    minHeight: 130,
    borderWidth: 1,
    borderColor: DS.bgSurface,
    textAlignVertical: "top",
  },
  inputLabel: {
    color: DS.white,
    fontSize: 14,
    marginBottom: 6,
    fontWeight: "600" as const,
    fontFamily: "Montserrat-SemiBold",
  },
  input: {
    backgroundColor: DS.bgInput,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    color: DS.white,
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    borderWidth: 1,
    borderColor: DS.bgSurface,
  },
  inputError: {
    borderColor: DS.danger,
  },
  profilePreviewCard: {
    backgroundColor: DS.bgCard,
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: DS.accent + "44",
  },
  previewGenreBadge: {
    alignSelf: "flex-start",
    backgroundColor: DS.accent + "33",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    marginBottom: 12,
  },
  previewGenreText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 10,
    color: DS.accentLight,
    letterSpacing: 1,
  },
  previewAvatarRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  previewAvatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: DS.bgSurface,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: DS.accent,
  },
  previewInfo: {
    flex: 1,
    gap: 5,
  },
  previewName: {
    fontFamily: "Montserrat-Bold",
    fontSize: 16,
    color: DS.white,
  },
  starsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  reviewsCount: {
    fontFamily: "Montserrat-Regular",
    fontSize: 11,
    color: DS.textSec,
    marginLeft: 4,
  },
  locationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  previewLocation: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textDis,
  },
  btnEnviar: {
    backgroundColor: DS.accent,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 28,
  },
  btnEnviarText: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 12,
    color: DS.white,
    letterSpacing: 1.5,
  },
  btnCancelar: {
    alignItems: "center",
    paddingVertical: 14,
    marginTop: 4,
  },
  btnCancelarText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 14,
    color: DS.textDis,
  },
});
