import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#09090F" },
  centered: {
    flex: 1,
    backgroundColor: "#09090F",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 32,
  },
  errorTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 18,
    color: "#FFFFFF",
    marginBottom: 8,
    textAlign: "center",
  },
  errorText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: "#8888AA",
    textAlign: "center",
    marginBottom: 24,
  },
  retryBtn: {
    backgroundColor: "#7B61FF",
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 24,
    marginBottom: 16,
  },
  retryBtnText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 13,
    color: "#FFFFFF",
    letterSpacing: 1,
  },
  backLink: { padding: 8 },
  backLinkText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 14,
    color: "#7B61FF",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 52,
    paddingHorizontal: 20,
    paddingBottom: 16,
  },
  backBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "rgba(123,97,255,0.12)",
    borderWidth: 1,
    borderColor: "#7B61FF",
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: { fontFamily: "Montserrat-Bold", fontSize: 18, color: "#FFFFFF" },
  headerSpacer: { width: 34 },
  scroll: { paddingHorizontal: 20, paddingBottom: 40 },
  sectionTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 14,
    color: "#FFFFFF",
    marginTop: 28,
    marginBottom: 12,
  },
  fieldLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 10,
    color: "#8888AA",
    letterSpacing: 2,
    marginBottom: 8,
    marginTop: 12,
  },
  input: {
    backgroundColor: "#13101F",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#1E1A30",
    paddingHorizontal: 16,
    paddingVertical: 14,
    color: "#FFFFFF",
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
  },
  inputReadOnly: {
    opacity: 0.7,
  },
  inputError: { borderColor: "#EF4444" },
  selector: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#13101F",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#1E1A30",
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  selectorDisabled: { opacity: 0.5 },
  selectorText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: "#FFFFFF",
    flex: 1,
  },
  selectorPlaceholder: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: "#555577",
    flex: 1,
  },
  orDivider: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: "#555577",
    textAlign: "center",
    marginVertical: 12,
  },
  photoSection: {
    alignItems: "center",
    marginTop: 8,
    marginBottom: 8,
  },
  generosErrorWrap: {
    borderWidth: 1,
    borderColor: "#EF4444",
    borderRadius: 10,
    padding: 8,
  },
  genreGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  genreChip: {
    width: "30%",
    aspectRatio: 1,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
  },
  genreChipSelected: {
    backgroundColor: "rgba(167,139,250,0.15)",
    borderColor: "#A78BFA",
  },
  genreChipIcon: { marginBottom: 8 },
  genreChipText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 11,
    color: "#888",
    textAlign: "center",
  },
  genreChipTextSelected: { color: "#A78BFA" },
  counterRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  counterLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 13,
    color: "#888",
  },
  counterValue: {
    fontFamily: "Montserrat-Bold",
    fontSize: 13,
    color: "#A78BFA",
  },
  radiusCard: {
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(167,139,250,0.2)",
    padding: 16,
    marginTop: 8,
    marginBottom: 16,
  },
  radiusCardTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 11,
    color: "#A78BFA",
    letterSpacing: 2,
    marginBottom: 8,
  },
  radiusValue: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 28,
    color: "#FFFFFF",
    marginBottom: 16,
  },
  radiusControls: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
  },
  radiusBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#A78BFA",
    alignItems: "center",
    justifyContent: "center",
  },
  radiusBtnLabel: {
    fontFamily: "Montserrat-Bold",
    fontSize: 16,
    color: "#FFFFFF",
    minWidth: 60,
    textAlign: "center",
  },
  venueGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 4,
  },
  venueChip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  venueChipSelected: {
    backgroundColor: "rgba(167,139,250,0.15)",
    borderColor: "#A78BFA",
  },
  venueChipText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 13,
    color: "#888",
  },
  venueChipTextSelected: { color: "#A78BFA" },
  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginTop: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  toggleLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 13,
    color: "#FFFFFF",
    flex: 1,
    marginRight: 12,
  },
  saveBtn: {
    backgroundColor: "#7B61FF",
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 32,
  },
  saveBtnDisabled: { opacity: 0.6 },
  saveBtnText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 14,
    color: "#FFFFFF",
    letterSpacing: 1,
  },
});
