import { StyleSheet } from "react-native";
import { DS } from "./constants";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: DS.bg },
  loading: { justifyContent: "center", alignItems: "center" },
  scroll: { paddingHorizontal: 20, paddingTop: 52, paddingBottom: 40 },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 28,
  },
  title: { fontFamily: "Montserrat-Bold", fontSize: 26, color: DS.textPrimary },
  subtitle: { fontFamily: "Montserrat-Regular", fontSize: 13, color: DS.textSecondary, marginTop: 4 },
  cancelBtn: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 13,
    color: DS.textSecondary,
    paddingTop: 6,
  },
  fieldLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 11,
    color: DS.textSecondary,
    letterSpacing: 2,
    marginBottom: 8,
    marginTop: 16,
  },
  fieldHint: {
    fontFamily: "Montserrat-Regular",
    fontSize: 11,
    color: DS.textSecondary,
    marginTop: 6,
    lineHeight: 16,
  },
  input: {
    backgroundColor: DS.surface,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 14,
    color: DS.textPrimary,
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    borderWidth: 1,
    borderColor: DS.border,
  },
  inputError: { borderColor: DS.danger },
  currencyRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: DS.surface,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: DS.border,
    paddingHorizontal: 14,
    paddingVertical: 4,
  },
  currencyRowError: { borderColor: DS.danger },
  currencyPrefix: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 14,
    color: DS.textSecondary,
    marginRight: 8,
    paddingVertical: 10,
  },
  currencyInput: {
    flex: 1,
    fontFamily: "Montserrat-Regular",
    fontSize: 15,
    color: DS.textPrimary,
    paddingVertical: 10,
    letterSpacing: 0.3,
  },
  dateBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: DS.surface,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: DS.border,
    gap: 10,
  },
  dateBtnText: { flex: 1, fontFamily: "Montserrat-Regular", fontSize: 14, color: DS.textPrimary },
  dateBtnPlaceholder: { color: DS.border },
  row: { flexDirection: "row", gap: 12 },
  flex: { flex: 1 },
  saleModeRow: { flexDirection: "row", gap: 8 },
  saleModeBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: DS.border,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
    backgroundColor: DS.surface,
  },
  saleModeBtnActive: { borderColor: DS.accent, backgroundColor: "rgba(123,97,255,0.2)" },
  saleModeBtnText: { fontFamily: "Montserrat-SemiBold", fontSize: 12, color: DS.textSecondary },
  saleModeBtnTextActive: { color: DS.textPrimary },
  coverPicker: {
    marginTop: 4,
    borderWidth: 1,
    borderColor: DS.border,
    borderRadius: 12,
    overflow: "hidden",
  },
  coverPreview: { width: "100%", height: 140 },
  coverPlaceholder: {
    width: "100%",
    height: 110,
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    backgroundColor: DS.surface,
  },
  coverPlaceholderText: { fontFamily: "Montserrat-SemiBold", fontSize: 12, color: DS.textSecondary },
  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 4 },
  chipRowError: {
    borderWidth: 1,
    borderColor: DS.danger,
    borderRadius: 10,
    padding: 8,
    marginTop: 4,
  },
  chip: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 16, borderWidth: 1.5 },
  chipText: { fontFamily: "Montserrat-Bold", fontSize: 12 },
  infoCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "rgba(123,97,255,0.1)",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(123,97,255,0.3)",
    padding: 16,
    marginTop: 24,
    marginBottom: 8,
  },
  infoIcon: { marginRight: 12 },
  infoText: {
    flex: 1,
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.textSecondary,
    lineHeight: 20,
  },
  publishBtn: {
    backgroundColor: DS.accent,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 16,
  },
  publishBtnDisabled: { opacity: 0.6 },
  publishBtnText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 14,
    color: DS.textPrimary,
    letterSpacing: 1,
  },
  modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.7)", justifyContent: "flex-end" },
  calendarSheet: {
    backgroundColor: DS.card,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    paddingBottom: 40,
  },
  calendarTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 13,
    color: DS.textSecondary,
    letterSpacing: 2,
    textAlign: "center",
    marginBottom: 16,
  },
});
