import { StyleSheet } from "react-native";
import { DS } from "./constants";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: DS.bg },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 52,
    marginBottom: 16,
  },
  avatarSmall: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: DS.card,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 8,
  },
  headerName: {
    flex: 1,
    fontFamily: "Montserrat-SemiBold",
    fontSize: 15,
    color: DS.accent,
  },
  searchBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: DS.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: DS.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginHorizontal: 20,
    marginBottom: 12,
  },
  searchInput: {
    flex: 1,
    color: DS.textPrimary,
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
  },
  list: { paddingHorizontal: 20, paddingBottom: 40, paddingTop: 4 },
  loading: { flex: 1, justifyContent: "center", alignItems: "center" },
  card: {
    backgroundColor: DS.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: DS.border,
    padding: 16,
    marginBottom: 12,
  },
  cardTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 10,
  },
  artistImg: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: DS.surface,
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  artistImgPhoto: { width: 72, height: 72 },
  genreBadge: {
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  genreBadgeText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 10,
    letterSpacing: 1,
  },
  artistName: {
    fontFamily: "Montserrat-Bold",
    fontSize: 17,
    color: DS.textPrimary,
    marginBottom: 2,
  },
  artistType: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textSecondary,
    marginBottom: 10,
  },
  cacheRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  cacheLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 11,
    color: DS.textSecondary,
    letterSpacing: 1,
  },
  cacheValue: {
    fontFamily: "Montserrat-Bold",
    fontSize: 14,
    color: DS.cyan,
  },
  ratingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginBottom: 12,
  },
  ratingText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 13,
    color: "#F39C12",
  },
  profileBtn: {
    backgroundColor: DS.accent,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
  },
  profileBtnText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 12,
    color: DS.textPrimary,
    letterSpacing: 1,
  },
  empty: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: DS.textSecondary,
    textAlign: "center",
    paddingTop: 40,
  },
});
