import { StyleSheet } from "react-native";
import { DS } from "./constants";
import { ActionButtonVariant } from "./types";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: DS.bg },
  center: { justifyContent: "center", alignItems: "center" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 52,
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: DS.border,
  },
  headerSpacer: { width: 18 },
  headerTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 17,
    color: DS.textPrimary,
  },
  scroll: { paddingHorizontal: 20, paddingTop: 28, paddingBottom: 40 },
  iconWrap: { alignItems: "center", marginBottom: 16 },
  iconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: `${DS.accent}22`,
    borderWidth: 2,
    borderColor: `${DS.accent}44`,
    justifyContent: "center",
    alignItems: "center",
  },
  title: {
    fontFamily: "Montserrat-Bold",
    fontSize: 20,
    color: DS.textPrimary,
    textAlign: "center",
  },
  subtitle: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: DS.textSecondary,
    textAlign: "center",
    marginTop: 6,
  },
  ref: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textMuted,
    textAlign: "center",
    marginTop: 4,
    marginBottom: 12,
  },
  badge: {
    alignSelf: "center",
    backgroundColor: `${DS.accent}22`,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 6,
    marginBottom: 20,
  },
  badgeText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 10,
    color: DS.accent,
    letterSpacing: 1,
  },
  successBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: `${DS.success}18`,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: `${DS.success}44`,
    padding: 12,
    marginBottom: 16,
  },
  successBannerText: {
    flex: 1,
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textSecondary,
    lineHeight: 18,
  },
  card: {
    backgroundColor: DS.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: DS.border,
    padding: 16,
    marginBottom: 16,
  },
  label: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 10,
    color: DS.textMuted,
    letterSpacing: 1.5,
    marginTop: 8,
  },
  value: {
    fontFamily: "Montserrat-Bold",
    fontSize: 15,
    color: DS.textPrimary,
  },
  valueHighlight: { color: DS.cyan },
  valueSm: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.textSecondary,
    lineHeight: 18,
  },
  divider: { height: 1, backgroundColor: DS.border, marginVertical: 12 },
  reviewSection: { marginBottom: 16 },
  reviewTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 11,
    color: DS.textMuted,
    letterSpacing: 1.5,
    marginBottom: 8,
  },
  reviewHint: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textSecondary,
    lineHeight: 18,
    marginBottom: 16,
  },
  infoCard: {
    flexDirection: "row",
    gap: 12,
    backgroundColor: `${DS.cyan}11`,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: `${DS.cyan}33`,
    padding: 14,
    marginBottom: 24,
  },
  infoText: {
    flex: 1,
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textSecondary,
    lineHeight: 18,
  },
  actionBtn: {
    borderRadius: 12,
    paddingVertical: 16,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
  },
  actionBtnPrimary: { backgroundColor: DS.accent },
  actionBtnCyan: { backgroundColor: DS.cyan },
  actionBtnSuccess: { backgroundColor: DS.success },
  actionBtnDanger: {
    borderWidth: 1.5,
    borderColor: DS.danger,
    paddingVertical: 14,
    backgroundColor: `${DS.danger}11`,
  },
  actionBtnSecondary: {
    borderWidth: 1.5,
    borderColor: DS.border,
    paddingVertical: 14,
  },
  actionBtnText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 12,
    color: "#fff",
    letterSpacing: 0.5,
    textAlign: "center",
  },
  actionBtnTextDanger: {
    fontFamily: "Montserrat-Bold",
    fontSize: 12,
    color: DS.danger,
    letterSpacing: 0.5,
  },
  actionBtnTextSecondary: {
    fontFamily: "Montserrat-Bold",
    fontSize: 13,
    color: DS.textSecondary,
  },
  disabled: { opacity: 0.5 },
});

export const actionButtonStyles: Record<ActionButtonVariant, object[]> = {
  primary: [styles.actionBtn, styles.actionBtnPrimary],
  cyan: [styles.actionBtn, styles.actionBtnCyan],
  success: [styles.actionBtn, styles.actionBtnSuccess],
  danger: [styles.actionBtn, styles.actionBtnDanger],
  secondary: [styles.actionBtn, styles.actionBtnSecondary],
};
