import { StyleSheet } from "react-native";
import { COVER_HEIGHT, DS, SCREEN_TOP_PADDING, SCREEN_WIDTH } from "./constants";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: DS.bg },
  loading: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: DS.bg },
  scroll: { flex: 1 },
  scrollContent: { paddingBottom: 40 },
  coverContainer: {
    width: SCREEN_WIDTH,
    height: COVER_HEIGHT,
    position: "relative",
    backgroundColor: DS.surface,
  },
  coverImage: { width: SCREEN_WIDTH, height: COVER_HEIGHT },
  coverOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(9,9,15,0.35)",
  },
  coverActions: {
    position: "absolute",
    top: SCREEN_TOP_PADDING,
    left: 16,
    right: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  coverActionBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  coverAvatarWrap: {
    position: "absolute",
    bottom: -44,
    alignSelf: "center",
    width: 88,
    height: 88,
    borderRadius: 44,
    borderWidth: 3,
    borderColor: DS.bg,
    backgroundColor: DS.surface,
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  coverAvatarImage: { width: "100%", height: "100%" },
  heroSection: {
    alignItems: "center",
    paddingTop: 56,
    paddingBottom: 20,
    paddingHorizontal: 20,
  },
  tipoLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 11,
    color: DS.accent,
    letterSpacing: 1.5,
    marginBottom: 6,
  },
  artistName: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 22,
    color: DS.textPrimary,
    textAlign: "center",
    marginBottom: 8,
    lineHeight: 30,
  },
  locationRow: { flexDirection: "row", alignItems: "center", gap: 6, marginBottom: 8 },
  locationText: { fontFamily: "Montserrat-Regular", fontSize: 13, color: DS.textSecondary },
  ratingRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  ratingValue: { fontFamily: "Montserrat-Bold", fontSize: 13, color: DS.gold },
  statsRow: {
    flexDirection: "row",
    marginHorizontal: 20,
    marginBottom: 24,
    backgroundColor: DS.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: DS.border,
    paddingVertical: 16,
  },
  statItem: { flex: 1, alignItems: "center" },
  statValue: {
    fontFamily: "Montserrat-Bold",
    fontSize: 16,
    color: DS.textPrimary,
    textAlign: "center",
  },
  statValueSmall: { fontSize: 12, lineHeight: 16 },
  statValueAmber: { color: DS.amber },
  statLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 9,
    color: DS.textSecondary,
    letterSpacing: 1.2,
    marginTop: 4,
  },
  statDivider: { width: 1, backgroundColor: DS.border },
  section: { paddingHorizontal: 20, marginBottom: 24 },
  sectionTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 16,
    color: DS.textPrimary,
    marginBottom: 12,
  },
  bodyText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: DS.textSecondary,
    lineHeight: 22,
  },
  emptyHint: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.textMuted,
    fontStyle: "italic",
  },
  infoCard: {
    backgroundColor: DS.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: DS.border,
    padding: 14,
    gap: 10,
  },
  infoRow: { gap: 2 },
  infoLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 10,
    color: DS.textMuted,
    letterSpacing: 1,
  },
  infoValue: { fontFamily: "Montserrat-Regular", fontSize: 14, color: DS.textPrimary },
  linkText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.accent,
    marginBottom: 8,
  },
  chipsWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chip: { paddingHorizontal: 14, paddingVertical: 6, borderRadius: 20, borderWidth: 1 },
  chipText: { fontFamily: "Montserrat-SemiBold", fontSize: 12 },
  instrumentChip: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    gap: 6,
  },
  instrumentChipText: { fontFamily: "Montserrat-SemiBold", fontSize: 12 },
  pressKitRow: { gap: 10 },
  pressKitImage: { width: 140, height: 140, borderRadius: 12, backgroundColor: DS.surface },
  showRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.05)",
  },
  showDateBlock: { width: 44, alignItems: "center" },
  showDate: {
    fontFamily: "Montserrat-Bold",
    fontSize: 12,
    color: DS.accent,
    textAlign: "center",
  },
  showInfo: { flex: 1 },
  showTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 13,
    color: DS.textPrimary,
    marginBottom: 2,
  },
  showVenue: {
    fontFamily: "Montserrat-Regular",
    fontSize: 11,
    color: DS.textSecondary,
  },
  buyTicketBtn: {
    backgroundColor: DS.accentSolid,
    borderRadius: 7,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  buyTicketText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 10,
    color: DS.textPrimary,
    letterSpacing: 0.5,
  },
  scrollBottomSpacer: { height: 100 },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
    backgroundColor: DS.bg,
  },
  errorTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 17,
    color: DS.textPrimary,
    textAlign: "center",
    marginBottom: 20,
  },
  errorBackBtn: {
    backgroundColor: DS.accentSolid,
    borderRadius: 10,
    paddingHorizontal: 24,
    paddingVertical: 12,
  },
  errorBackBtnText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 13,
    color: DS.textPrimary,
    letterSpacing: 1,
  },
  stickyBottom: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#0D0D14",
    borderTopWidth: 1,
    borderTopColor: DS.border,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 28,
  },
  backBottomBtn: {
    backgroundColor: DS.accentSolid,
    borderRadius: 12,
    paddingVertical: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  backBottomBtnText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 14,
    color: DS.textPrimary,
    letterSpacing: 1,
  },
});
