import { StyleSheet } from "react-native";
import { DS } from "./constants";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: DS.bg },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 52,
    paddingHorizontal: 20,
    paddingBottom: 12,
  },
  headerBrand: {
    fontFamily: "Montserrat-Bold",
    fontSize: 14,
    color: DS.accent,
    letterSpacing: 2,
  },
  pageTitleArea: { paddingHorizontal: 20, marginBottom: 16 },
  pageTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 22,
    color: DS.white,
    marginBottom: 4,
  },
  pageSubtitle: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.textSec,
  },
  tabsRow: {
    flexDirection: "row",
    marginHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.06)",
    marginBottom: 16,
  },
  tab: {
    flex: 1,
    paddingVertical: 12,
    alignItems: "center",
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
  },
  tabActive: { borderBottomColor: DS.accent },
  tabText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 12,
    color: DS.textDis,
    letterSpacing: 1,
  },
  tabTextActive: { color: DS.accent },
  loadingIndicator: { marginTop: 40 },
  scrollContent: { paddingHorizontal: 20, paddingBottom: 20 },
  scrollBottomSpacer: { height: 20 },
  emptyText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: DS.textDis,
    textAlign: "center",
    marginTop: 40,
  },
  showCard: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    overflow: "hidden",
    marginBottom: 16,
  },
  showImage: {
    height: 130,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    overflow: "hidden",
  },
  showCoverImage: {
    ...StyleSheet.absoluteFillObject,
    width: "100%",
    height: "100%",
  },
  daysBadge: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: "rgba(167,139,250,0.9)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
  },
  daysBadgeText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 9,
    color: DS.white,
    letterSpacing: 0.5,
  },
  showBody: { padding: 14 },
  showBodyTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  showDate: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 12,
    color: DS.accent,
  },
  showTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 16,
    color: DS.white,
    marginBottom: 4,
  },
  showVenue: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textSec,
    marginBottom: 12,
  },
  showFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  showPrice: {
    fontFamily: "Montserrat-Bold",
    fontSize: 16,
    color: DS.price,
  },
  artistGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  artistCard: {
    width: "47%",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    padding: 14,
  },
  artistAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
    position: "relative",
    overflow: "hidden",
  },
  artistAvatarImage: {
    width: "100%",
    height: "100%",
  },
  artistHeartOverlay: {
    position: "absolute",
    bottom: -4,
    right: -4,
    backgroundColor: "rgba(167,139,250,0.2)",
    borderRadius: 10,
    padding: 4,
  },
  artistName: {
    fontFamily: "Montserrat-Bold",
    fontSize: 13,
    color: DS.white,
    textAlign: "center",
    marginBottom: 3,
  },
  artistGenre: {
    fontFamily: "Montserrat-Regular",
    fontSize: 11,
    color: DS.textSec,
    textAlign: "center",
  },
  venueCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    padding: 12,
    marginBottom: 10,
  },
  venueCardPressable: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  venueImage: {
    width: 60,
    height: 60,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  venueImageCover: {
    width: "100%",
    height: "100%",
  },
  venueInfo: { flex: 1 },
  venueName: {
    fontFamily: "Montserrat-Bold",
    fontSize: 14,
    color: DS.white,
    marginBottom: 2,
  },
  venueCityRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  venueCity: {
    fontFamily: "Montserrat-Regular",
    fontSize: 11,
    color: DS.textSec,
  },
  venueHeartBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(167,139,250,0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
});
