import { StyleSheet } from "react-native";
import { DS } from "./constants";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: DS.bg },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 52,
    marginBottom: 16,
  },
  avatarSmall: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: DS.card,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 8,
  },
  headerName: {
    flex: 1,
    fontFamily: "Montserrat-SemiBold",
    fontSize: 15,
    color: DS.accent,
  },
  title: {
    fontFamily: "Montserrat-Bold",
    fontSize: 26,
    color: DS.textPrimary,
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  tabs: {
    flexDirection: "row",
    paddingHorizontal: 20,
    gap: 8,
    marginBottom: 16,
  },
  tabBtn: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: DS.border,
  },
  tabBtnOn: {
    backgroundColor: DS.accent,
    borderColor: DS.accent,
  },
  tabBtnText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 11,
    color: DS.textSecondary,
    letterSpacing: 1,
  },
  tabBtnTextOn: {
    color: DS.textPrimary,
  },
  list: { paddingHorizontal: 20, paddingBottom: 100 },
  loading: { flex: 1, justifyContent: "center", alignItems: "center" },
  card: {
    backgroundColor: DS.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: DS.border,
    padding: 16,
    marginBottom: 12,
  },
  cardTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  genreRow: { flexDirection: "row", flexWrap: "wrap", gap: 6, flex: 1, marginRight: 10 },
  genreBadge: { borderWidth: 1, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 3 },
  genreBadgeText: { fontFamily: "Montserrat-Bold", fontSize: 10, letterSpacing: 1 },
  cardTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 16,
    color: DS.textPrimary,
    marginBottom: 8,
  },
  cardMeta: { flexDirection: "row", alignItems: "center", gap: 6, marginBottom: 4 },
  cardMetaText: { fontFamily: "Montserrat-Regular", fontSize: 13, color: DS.textSecondary },
  cardMetaTextHighlight: { color: DS.cyan },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: DS.surface,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 5,
    alignSelf: "flex-start",
    marginTop: 6,
  },
  badgeContratado: { borderWidth: 1, borderColor: "#00C85333" },
  badgeIcon: { marginRight: 6 },
  badgeText: { fontFamily: "Montserrat-Regular", fontSize: 12, color: DS.textSecondary },
  badgeTextSuccess: { color: DS.success },
  empty: { alignItems: "center", paddingTop: 60, gap: 12 },
  emptyText: { fontFamily: "Montserrat-Regular", fontSize: 14, color: DS.textSecondary },
  fab: {
    position: "absolute",
    bottom: 88,
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: DS.accent,
    justifyContent: "center",
    alignItems: "center",
    elevation: 4,
  },
});
