import { StyleSheet } from "react-native";
import { DS } from "./constants";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: DS.bg },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 52,
    paddingHorizontal: 20,
    paddingBottom: 16,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: DS.card,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: DS.border,
  },
  headerTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 17,
    color: DS.textPrimary,
  },
  headerSpacer: { width: 36 },
  scroll: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  summaryCard: {
    backgroundColor: DS.card,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: DS.border,
    padding: 20,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    marginBottom: 8,
  },
  artistSection: {
    alignItems: "center",
    marginBottom: 8,
    gap: 10,
  },
  avatarWrap: {
    width: 88,
    height: 88,
    borderRadius: 44,
    borderWidth: 2,
    borderColor: DS.accent,
    padding: 3,
  },
  avatar: {
    width: "100%",
    height: "100%",
    borderRadius: 40,
  },
  avatarFallback: {
    width: "100%",
    height: "100%",
    borderRadius: 40,
    backgroundColor: DS.surface,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: DS.border,
  },
  artistName: {
    fontFamily: "Montserrat-Bold",
    fontSize: 17,
    color: DS.textPrimary,
    textAlign: "center",
  },
  confirmedPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    backgroundColor: "rgba(0,200,83,0.12)",
    borderWidth: 1,
    borderColor: "rgba(0,200,83,0.25)",
  },
  confirmedText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 11,
    color: DS.success,
  },
  row: { gap: 6 },
  rowLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 11,
    color: DS.textSecondary,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  rowValue: {
    fontFamily: "Montserrat-Bold",
    fontSize: 16,
    color: DS.textPrimary,
    lineHeight: 22,
  },
  divider: {
    height: 1,
    backgroundColor: DS.border,
    marginVertical: 16,
  },
});
