import { StyleSheet } from "react-native";
import { DS } from "./constants";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: DS.bg },
  scrollContent: { padding: 20, gap: 16 },
  pageTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 22,
    color: DS.white,
    marginBottom: 4,
  },
  pageSubtitle: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.textMuted,
    marginBottom: 8,
    lineHeight: 20,
  },
  sectionCard: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    padding: 16,
  },
  sectionLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 14,
  },
  sectionLabel: {
    fontFamily: "Montserrat-Bold",
    fontSize: 11,
    color: DS.accent,
    letterSpacing: 2,
  },
  settingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 4,
  },
  settingTitle: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 13,
    color: DS.white,
    marginBottom: 2,
  },
  settingValue: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textMuted,
  },
  smallBtn: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(167,139,250,0.3)",
  },
  smallBtnText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 12,
    color: DS.accent,
  },
  dangerLink: { paddingVertical: 8 },
  dangerLinkText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 13,
    color: DS.danger,
  },
  divider: {
    height: 1,
    backgroundColor: "rgba(255,255,255,0.06)",
    marginVertical: 10,
  },
  profileActionCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 8,
  },
  profileActionIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(167,139,250,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  profileActionInfo: { flex: 1 },
  profileActionTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 14,
    color: DS.white,
    marginBottom: 2,
  },
  profileActionSubtitle: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textMuted,
  },
  signOutBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,107,107,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,107,107,0.3)",
    borderRadius: 12,
    paddingVertical: 15,
  },
  signOutText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 14,
    color: DS.danger,
    letterSpacing: 1.5,
  },
  footer: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.footer,
    textAlign: "center",
    letterSpacing: 2,
  },
  scrollBottomSpacer: { height: 32 },
  modal: { justifyContent: "flex-end", margin: 0 },
  modalSheet: {
    backgroundColor: DS.modalBg,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 24,
    paddingBottom: 36,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  modalTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 16,
    color: DS.white,
  },
  modalHint: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.textMuted,
    marginBottom: 16,
    lineHeight: 20,
  },
  modalLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 12,
    color: DS.textMuted,
    marginBottom: 6,
    marginTop: 4,
  },
  modalInput: {
    backgroundColor: "rgba(255,255,255,0.06)",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: DS.white,
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    marginBottom: 4,
  },
  modalInputError: {
    borderColor: "#EF4444",
  },
  modalBtn: {
    backgroundColor: DS.accent,
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 8,
  },
  modalBtnDanger: { backgroundColor: "#E53E3E" },
  modalBtnText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 13,
    color: DS.white,
    letterSpacing: 1,
  },
});

export const headerStyles = StyleSheet.create({
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 52,
    paddingHorizontal: 20,
    paddingBottom: 12,
  },
  backBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "rgba(167,139,250,0.15)",
    borderWidth: 1,
    borderColor: DS.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  headerBrand: {
    fontFamily: "Montserrat-Bold",
    fontSize: 14,
    color: DS.accent,
    letterSpacing: 2,
  },
});
