import { StyleSheet } from "react-native";
import { DS } from "./constants";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: DS.bg },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 52,
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: DS.border,
  },
  headerSpacer: { width: 18 },
  headerTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 17,
    color: DS.textPrimary,
  },
  scroll: { paddingHorizontal: 20, paddingTop: 32, paddingBottom: 40 },
  banner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderRadius: 10,
    borderWidth: 1,
    padding: 12,
    marginBottom: 20,
  },
  bannerText: {
    flex: 1,
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textSecondary,
    lineHeight: 18,
  },
  iconWrap: { alignItems: "center", marginBottom: 20 },
  iconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: `${DS.accent}22`,
    borderWidth: 2,
    borderColor: `${DS.accent}44`,
    justifyContent: "center",
    alignItems: "center",
  },
  title: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: DS.textSecondary,
    textAlign: "center",
    marginBottom: 6,
  },
  gigTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 20,
    color: DS.textPrimary,
    textAlign: "center",
    marginBottom: 12,
  },
  statusPill: {
    alignSelf: "center",
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
    borderWidth: 1,
    marginBottom: 24,
  },
  statusPillText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 10,
    letterSpacing: 1.2,
  },
  infoCard: {
    backgroundColor: DS.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: DS.border,
    padding: 16,
    marginBottom: 12,
  },
  infoRow: { flexDirection: "row", alignItems: "center" },
  infoBody: { flex: 1, marginLeft: 14 },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: DS.surface,
    justifyContent: "center",
    alignItems: "center",
  },
  label: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 10,
    color: DS.textMuted,
    letterSpacing: 1.5,
    marginBottom: 4,
  },
  value: {
    fontFamily: "Montserrat-Bold",
    fontSize: 16,
    color: DS.textPrimary,
  },
  valueHighlight: { color: DS.cyan },
  valueSection: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: DS.border,
  },
  messageCard: {
    backgroundColor: DS.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: DS.border,
    padding: 16,
    marginBottom: 12,
  },
  messageText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.textSecondary,
    lineHeight: 20,
  },
  refCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: DS.surface,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 20,
  },
  refText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textMuted,
  },
  warningCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    backgroundColor: `${DS.cyan}11`,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: `${DS.cyan}33`,
    padding: 14,
    marginBottom: 28,
  },
  warningBody: { flex: 1 },
  warningTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 11,
    color: DS.cyan,
    letterSpacing: 1.5,
    marginBottom: 4,
  },
  warningText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textSecondary,
    lineHeight: 18,
  },
  btnAccept: {
    backgroundColor: DS.accent,
    borderRadius: 12,
    paddingVertical: 16,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
  },
  btnReaccept: {
    backgroundColor: DS.danger,
    borderRadius: 12,
    paddingVertical: 16,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
  },
  btnAcceptText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 13,
    color: "#fff",
    letterSpacing: 0.5,
  },
  btnReject: {
    borderWidth: 1.5,
    borderColor: DS.danger,
    borderRadius: 12,
    paddingVertical: 14,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
    marginBottom: 20,
  },
  btnRejectText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 13,
    color: DS.danger,
  },
  btnProfile: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
  },
  btnProfileText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 13,
    color: DS.accent,
  },
  disabled: { opacity: 0.5 },
});
