import { StyleSheet } from "react-native";
import { colors } from "@/utils/colors";

export const onboardingStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.background,
  },
  kav: {
    flex: 1,
  },
  scroll: {
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 24,
  },
  scrollWithFooter: {
    paddingBottom: 8,
  },
  footer: {
    paddingHorizontal: 24,
    paddingBottom: 32,
    paddingTop: 12,
    backgroundColor: colors.background,
    borderTopWidth: 1,
    borderTopColor: colors.divider,
  },
  stepMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 20,
  },
  stepLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 11,
    color: colors.textMuted,
    letterSpacing: 2,
  },
  stepName: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 11,
    color: colors.purpleLight,
    letterSpacing: 2,
  },
  title: {
    fontFamily: "Montserrat-Bold",
    fontSize: 26,
    color: colors.white,
    lineHeight: 34,
    marginBottom: 10,
  },
  titleAccent: {
    color: colors.purpleLight,
  },
  subtitle: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: colors.textMuted,
    lineHeight: 22,
    marginBottom: 24,
  },
  sectionLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 11,
    color: colors.textMuted,
    letterSpacing: 2,
    marginBottom: 10,
    marginTop: 8,
  },
  fieldLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 10,
    color: colors.textMuted,
    letterSpacing: 2,
    marginBottom: 6,
  },
  uploadBox: {
    backgroundColor: colors.surface,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: colors.inputBorder,
    borderStyle: "dashed",
    paddingVertical: 32,
    alignItems: "center",
    marginBottom: 24,
    gap: 8,
  },
  uploadLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 12,
    color: colors.purpleLight,
    letterSpacing: 2,
    marginTop: 4,
  },
  uploadSub: {
    fontFamily: "Montserrat-Regular",
    fontSize: 11,
    color: colors.textMuted,
    textAlign: "center",
  },
  uploadPreview: {
    width: "100%",
    height: 120,
    borderRadius: 12,
  },
  row: {
    flexDirection: "row",
    gap: 12,
  },
  selector: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.purpleBlack2,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: colors.inputBorder,
  },
  selectorDisabled: {
    opacity: 0.5,
  },
  selectorEmpty: {
    borderColor: colors.inputBorder,
  },
  selectorText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: colors.white,
    flex: 1,
  },
  selectorPlaceholder: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: colors.textMuted,
    flex: 1,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    padding: 16,
  },
  btnPrimary: {
    backgroundColor: colors.purplePrimary,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: "center",
    marginBottom: 12,
  },
  btnPrimaryDisabled: {
    opacity: 0.6,
  },
  btnPrimaryText: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 13,
    color: colors.white,
    letterSpacing: 1.5,
  },
  btnGhost: {
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.inputBorder,
  },
  btnGhostText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 13,
    color: colors.textMuted,
    letterSpacing: 1,
  },
  btnLink: {
    paddingVertical: 14,
    alignItems: "center",
  },
  btnLinkText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 13,
    color: colors.textMuted,
    textDecorationLine: "underline",
  },
  bioContainer: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    overflow: "hidden",
  },
  bioInput: {
    color: colors.white,
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    lineHeight: 22,
    padding: 16,
    minHeight: 140,
  },
  bioCounter: {
    fontFamily: "Montserrat-Regular",
    fontSize: 11,
    color: colors.textMuted,
    textAlign: "right",
    paddingHorizontal: 14,
    paddingBottom: 10,
  },
  galeriaNote: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: colors.textMuted,
    marginBottom: 12,
  },
  galeriaScroll: {
    marginHorizontal: -24,
  },
  galeriaContent: {
    paddingHorizontal: 24,
    gap: 10,
    paddingBottom: 4,
  },
  fotoAdd: {
    width: 90,
    height: 90,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: colors.purplePrimary,
    borderStyle: "dashed",
    backgroundColor: colors.accentSoftBg,
    justifyContent: "center",
    alignItems: "center",
    gap: 6,
  },
  fotoAddLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 9,
    color: colors.purpleLight,
    letterSpacing: 1,
    textAlign: "center",
  },
  fotoThumb: {
    width: 90,
    height: 90,
    borderRadius: 12,
    overflow: "hidden",
    position: "relative",
  },
  fotoImage: {
    width: 90,
    height: 90,
  },
  fotoRemove: {
    position: "absolute",
    top: 4,
    right: 4,
    backgroundColor: colors.overlayDarkSoft,
    borderRadius: 10,
  },
});
