import { StyleSheet } from "react-native";
import { DS, SCREEN_TOP_PADDING } from "./constants";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: DS.bg,
  },
  progressBg: {
    width: "100%",
    height: 4,
    backgroundColor: DS.bgCard,
  },
  progressFill: {
    height: 4,
    backgroundColor: DS.accent,
    borderRadius: 2,
  },
  scroll: {
    paddingHorizontal: 24,
    paddingTop: SCREEN_TOP_PADDING,
    paddingBottom: 60,
  },
  headerLabel: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 10,
    color: DS.accent,
    letterSpacing: 3,
    marginBottom: 8,
  },
  stepLabel: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.textSec,
    marginBottom: 20,
  },
  sectionTitle: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 20,
    color: DS.white,
    marginBottom: 8,
    lineHeight: 28,
  },
  sectionSubtitle: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.textSec,
    marginBottom: 20,
    lineHeight: 20,
  },
  fieldLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 11,
    color: DS.textSec,
    letterSpacing: 2,
    marginBottom: 8,
    marginTop: 16,
  },
  input: {
    backgroundColor: DS.bgInput,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 13,
    color: DS.white,
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    borderWidth: 1,
    borderColor: DS.bgSurface,
  },
  inputError: {
    borderColor: DS.danger,
  },
  textarea: {
    minHeight: 120,
    paddingTop: 12,
    textAlignVertical: "top",
  },
  selector: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: DS.bgInput,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: DS.bgSurface,
  },
  selectorEmpty: {
    borderColor: DS.bgSurface,
  },
  selectorError: {
    borderColor: DS.danger,
  },
  selectorDisabled: {
    opacity: 0.5,
  },
  selectorText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: DS.white,
    flex: 1,
  },
  selectorPlaceholder: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: DS.textSec,
    flex: 1,
  },
  mapCard: {
    backgroundColor: DS.bgCard,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    height: 110,
    marginTop: 16,
    borderWidth: 1,
    borderColor: DS.bgSurface,
  },
  mapLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 12,
    color: DS.textSec,
    letterSpacing: 2,
    marginTop: 8,
  },
  mapSub: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textDis,
    marginTop: 4,
  },
  separator: {
    height: 1,
    backgroundColor: DS.bgSurface,
    marginVertical: 28,
  },
  rowBetween: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  charCount: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textDis,
    marginTop: 16,
  },
  linkChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: DS.bgCard,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 6,
    gap: 8,
  },
  linkText: {
    flex: 1,
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textSec,
  },
  linkInputRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 8,
    alignItems: "center",
  },
  btnAddSmall: {
    backgroundColor: DS.accent,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 13,
  },
  btnAddSmallText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 12,
    color: DS.white,
  },
  btnOutline: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: DS.accentLight,
    borderRadius: 10,
    paddingVertical: 13,
    marginTop: 10,
    gap: 8,
  },
  btnOutlineText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 13,
    color: DS.accentLight,
    letterSpacing: 1,
  },
  pressKitThumb: {
    width: 80,
    height: 80,
    borderRadius: 8,
    marginRight: 8,
    position: "relative",
  },
  pressKitImage: {
    width: 80,
    height: 80,
    borderRadius: 8,
  },
  pressKitRemove: {
    position: "absolute",
    top: 4,
    right: 4,
    backgroundColor: DS.danger,
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  uploadArea: {
    borderWidth: 1,
    borderColor: DS.bgSurface,
    borderStyle: "dashed",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 28,
    marginTop: 4,
    gap: 8,
    backgroundColor: DS.bgCard,
  },
  uploadAreaError: {
    borderColor: DS.danger,
  },
  uploadLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 12,
    color: DS.textSec,
    letterSpacing: 1,
  },
  uploadSub: {
    fontFamily: "Montserrat-Regular",
    fontSize: 11,
    color: DS.textDis,
  },
  btnPrimary: {
    backgroundColor: DS.accent,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 32,
  },
  btnPrimaryText: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 12,
    color: DS.white,
    letterSpacing: 1.5,
  },
  btnBack: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginTop: 16,
    paddingVertical: 10,
  },
  btnBackText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 13,
    color: DS.textSec,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.7)",
    justifyContent: "flex-end",
  },
  modalContainer: {
    backgroundColor: DS.bgInput,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: "80%",
    paddingBottom: 32,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: DS.bgSurface,
  },
  modalTitle: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 16,
    color: DS.white,
  },
  searchBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: DS.bgCard,
    borderRadius: 10,
    marginHorizontal: 16,
    marginVertical: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: DS.bgSurface,
  },
  searchInput: {
    flex: 1,
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: DS.white,
  },
  pickerItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: DS.bgSurface,
    gap: 12,
  },
  pickerItemActive: {
    backgroundColor: DS.accent + "22",
  },
  pickerItemSigla: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 12,
    color: DS.accent,
    width: 30,
  },
  pickerItemNome: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: DS.white,
    flex: 1,
  },
});
