import { StyleSheet } from "react-native";
import { COVER_HEIGHT, DS, SCREEN_WIDTH } from "./constants";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: DS.bg },
  loading: { justifyContent: "center", alignItems: "center" },
  coverContainer: {
    width: SCREEN_WIDTH,
    height: COVER_HEIGHT,
    position: "relative",
    backgroundColor: DS.surface,
  },
  coverImage: { width: SCREEN_WIDTH, height: COVER_HEIGHT },
  coverOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(9,9,15,0.35)",
  },
  coverActions: {
    position: "absolute",
    top: 52,
    left: 16,
    right: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  coverActionBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "center",
    alignItems: "center",
  },
  coverAvatarWrap: {
    position: "absolute",
    bottom: -40,
    alignSelf: "center",
    width: 88,
    height: 88,
    borderRadius: 44,
    borderWidth: 3,
    borderColor: DS.bg,
    backgroundColor: DS.surface,
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  coverAvatarImage: { width: "100%", height: "100%" },
  scroll: { paddingBottom: 40 },
  heroSection: {
    alignItems: "center",
    paddingTop: 52,
    paddingBottom: 24,
    paddingHorizontal: 20,
  },
  artistName: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 18,
    color: DS.textPrimary,
    textAlign: "center",
    marginBottom: 6,
  },
  tipoLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 12,
    color: DS.accent,
    letterSpacing: 1.5,
    marginBottom: 8,
  },
  locationRow: { flexDirection: "row", alignItems: "center", gap: 4 },
  locationText: { fontFamily: "Montserrat-Regular", fontSize: 12, color: DS.textSecondary },
  statsRow: {
    flexDirection: "row",
    marginHorizontal: 20,
    marginBottom: 24,
    backgroundColor: DS.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: DS.border,
    paddingVertical: 16,
  },
  statItem: { flex: 1, alignItems: "center" },
  statValue: {
    fontFamily: "Montserrat-Bold",
    fontSize: 18,
    color: DS.textPrimary,
    textAlign: "center",
  },
  statValueAmber: { color: DS.amber },
  statLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 9,
    color: DS.textSecondary,
    letterSpacing: 1.2,
    marginTop: 4,
  },
  statDivider: { width: 1, backgroundColor: DS.border },
  section: { paddingHorizontal: 20, marginBottom: 24 },
  sectionTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 16,
    color: DS.textPrimary,
    marginBottom: 10,
  },
  bodyText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.textSecondary,
    lineHeight: 21,
  },
  emptyHint: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.textMuted,
    fontStyle: "italic",
  },
  infoCard: {
    backgroundColor: DS.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: DS.border,
    padding: 14,
    gap: 10,
  },
  infoRow: { gap: 2 },
  infoLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 10,
    color: DS.textMuted,
    letterSpacing: 1,
  },
  infoValue: { fontFamily: "Montserrat-Regular", fontSize: 14, color: DS.textPrimary },
  linkText: { fontFamily: "Montserrat-Regular", fontSize: 13, color: DS.cyan, marginBottom: 8 },
  chipsWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chip: { paddingHorizontal: 14, paddingVertical: 6, borderRadius: 20, borderWidth: 1 },
  chipText: { fontFamily: "Montserrat-SemiBold", fontSize: 12 },
  instrumentChip: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  instrumentChipText: { fontFamily: "Montserrat-SemiBold", fontSize: 12 },
  pressKitRow: { gap: 10 },
  pressKitImage: { width: 110, height: 110, borderRadius: 10, backgroundColor: DS.surface },
  scrollBottomSpacer: { height: 88 },
  errorContainer: {
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  errorIcon: { marginBottom: 16 },
  errorTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 17,
    color: DS.textPrimary,
    textAlign: "center",
    marginBottom: 8,
  },
  errorMessage: { textAlign: "center", marginBottom: 24 },
  errorBackBtn: {
    backgroundColor: DS.accent,
    borderRadius: 10,
    paddingHorizontal: 24,
    paddingVertical: 12,
  },
  errorBackBtnText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 13,
    color: DS.textPrimary,
    letterSpacing: 1,
  },
  stickyBottom: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#0D0D14",
    borderTopWidth: 1,
    borderTopColor: DS.border,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 28,
  },
  backBottomBtn: {
    backgroundColor: DS.accent,
    borderRadius: 12,
    paddingVertical: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  backBottomBtnIcon: { marginRight: 8 },
  backBottomBtnText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 14,
    color: DS.textPrimary,
    letterSpacing: 1,
  },
});
