import { StyleSheet } from "react-native";
import { DS } from "./constants";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: DS.bg },
  header: {
    paddingTop: 52,
    paddingHorizontal: 20,
    paddingBottom: 12,
  },
  headerText: { flex: 1 },
  headerTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 20,
    color: DS.white,
    marginBottom: 4,
  },
  headerSubtitle: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.textSec,
    lineHeight: 19,
  },
  tabsRow: {
    flexDirection: "row",
    marginHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.06)",
    marginBottom: 12,
  },
  tab: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
  },
  tabActive: { borderBottomColor: DS.accent },
  tabText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 13,
    color: DS.textDis,
    letterSpacing: 0.5,
  },
  tabTextActive: { color: DS.accent },
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  scrollContent: { paddingHorizontal: 20, paddingBottom: 20, gap: 8 },
  scrollBottomSpacer: { height: 20 },
  emptyText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: DS.textDis,
    textAlign: "center",
    marginTop: 40,
    marginBottom: 24,
  },
  ticketCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    padding: 10,
  },
  ticketThumb: {
    width: 44,
    height: 44,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  ticketInfo: { flex: 1, minWidth: 0 },
  genreText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 8,
    letterSpacing: 0.8,
    marginBottom: 2,
  },
  ticketTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 13,
    color: DS.white,
    marginBottom: 2,
  },
  ticketMeta: {
    fontFamily: "Montserrat-Regular",
    fontSize: 11,
    color: DS.textSec,
  },
  ticketDate: {
    fontFamily: "Montserrat-Regular",
    fontSize: 10,
    color: DS.textDis,
    marginTop: 2,
  },
  ticketFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 4,
  },
  ticketPrice: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 11,
    color: DS.price,
  },
  daysText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 10,
    color: DS.accent,
  },
  rateBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(167,139,250,0.1)",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  exploreCard: {
    backgroundColor: "rgba(167,139,250,0.08)",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(167,139,250,0.2)",
    padding: 16,
    alignItems: "center",
    marginTop: 8,
  },
  exploreIcon: { marginBottom: 8 },
  exploreTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 14,
    color: DS.white,
    marginBottom: 4,
    textAlign: "center",
  },
  exploreSubtitle: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textSec,
    textAlign: "center",
    lineHeight: 18,
    marginBottom: 12,
  },
  exploreBtn: {
    backgroundColor: DS.accentBtn,
    borderRadius: 8,
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  exploreBtnText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 12,
    color: DS.white,
    letterSpacing: 0.5,
  },
});
