import { StyleSheet } from "react-native";
import { DS, SCREEN_TOP_PADDING } from "./constants";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: DS.bg },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: SCREEN_TOP_PADDING,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: DS.border,
  },
  headerSpacer: { width: 18 },
  headerTitle: {
    fontFamily: "Montserrat-Bold",
    fontSize: 16,
    letterSpacing: 0.5,
    color: DS.textPrimary,
  },
  loading: { flex: 1, justifyContent: "center", alignItems: "center" },
  list: { padding: 20, gap: 12, paddingBottom: 40 },
  emptyWrap: { flex: 1, justifyContent: "center", alignItems: "center" },
  emptyText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    textAlign: "center",
    color: DS.textSecondary,
  },
  showCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: DS.card,
    borderRadius: 12,
    padding: 14,
    borderLeftWidth: 3,
    gap: 12,
  },
  dateBadge: {
    width: 44,
    height: 44,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  dateDay: { fontFamily: "Montserrat-Bold", fontSize: 16, lineHeight: 18, color: DS.textPrimary },
  dateMes: { fontFamily: "Montserrat-Bold", fontSize: 9, letterSpacing: 0.5 },
  showCardBody: { flex: 1, gap: 3 },
  showTitle: { fontFamily: "Montserrat-Bold", fontSize: 14, color: DS.textPrimary },
  showSub: { fontFamily: "Montserrat-Regular", fontSize: 11, color: DS.textSecondary },
  confirmedBadge: { flexDirection: "row", alignItems: "center", gap: 4, marginTop: 2 },
  confirmedBadgeText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 9,
    letterSpacing: 0.3,
    color: DS.success,
  },
  genreRow: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginTop: 6 },
  genreBadge: { borderWidth: 1, borderRadius: 10, paddingHorizontal: 8, paddingVertical: 2 },
  genreBadgeText: { fontFamily: "Montserrat-Bold", fontSize: 9, letterSpacing: 0.5 },
});
