import { StyleSheet } from "react-native";
import { DS } from "./constants";
import { SCREEN_TOP_PADDING } from "../constants";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: DS.bg,
  },
  progressBg: {
    width: "100%",
    height: 4,
    backgroundColor: DS.bgCard,
  },
  progressFill: {
    height: 4,
    backgroundColor: DS.accent,
    borderRadius: 2,
  },
  scroll: {
    paddingHorizontal: 24,
    paddingTop: SCREEN_TOP_PADDING,
    paddingBottom: 60,
  },
  headerLabel: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 10,
    color: DS.accent,
    letterSpacing: 3,
    marginBottom: 8,
  },
  title: {
    fontFamily: "Montserrat-Bold",
    fontSize: 26,
    color: DS.white,
    marginBottom: 4,
  },
  stepLabel: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.textSec,
    marginBottom: 28,
  },
  fieldLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 11,
    color: DS.textSec,
    letterSpacing: 2,
    marginBottom: 8,
    marginTop: 16,
  },
  sectionLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 11,
    color: DS.textSec,
    letterSpacing: 2,
    marginBottom: 8,
    marginTop: 16,
  },
  input: {
    backgroundColor: DS.bgInput,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 13,
    color: DS.white,
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    borderWidth: 1,
    borderColor: DS.bgSurface,
  },
  inputError: {
    borderColor: DS.danger,
  },
  avatarArea: {
    alignSelf: "center",
    width: 110,
    height: 110,
    borderRadius: 55,
    borderWidth: 2,
    borderColor: DS.accent,
    borderStyle: "dashed",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 8,
    backgroundColor: DS.bgCard,
    overflow: "hidden",
  },
  avatarAreaError: {
    borderColor: DS.danger,
  },
  avatarImage: {
    width: 110,
    height: 110,
    borderRadius: 55,
  },
  avatarLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 10,
    color: DS.accent,
    marginTop: 6,
    letterSpacing: 1.5,
  },
  trocarFotoBtn: {
    alignSelf: "center",
    marginBottom: 20,
  },
  trocarFotoText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.accentLight,
  },
  photoErrorWrap: {
    alignSelf: "center",
    width: "100%",
    marginBottom: 4,
  },
  pillRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 4,
  },
  pillRowError: {
    borderWidth: 1,
    borderColor: DS.danger,
    borderRadius: 10,
    padding: 8,
  },
  pill: {
    paddingHorizontal: 18,
    paddingVertical: 9,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: DS.textDis,
    backgroundColor: DS.bgCard,
  },
  pillActive: {
    borderColor: DS.accent,
    backgroundColor: DS.accent + "22",
  },
  pillText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 13,
    color: DS.textSec,
  },
  pillTextActive: {
    color: DS.accentLight,
  },
  separator: {
    height: 1,
    backgroundColor: DS.bgSurface,
    marginVertical: 20,
  },
  rowBetween: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  multiLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 10,
    color: DS.cyan,
    letterSpacing: 1.5,
  },
  generoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  generosErrorWrap: {
    borderWidth: 1,
    borderColor: DS.danger,
    borderRadius: 10,
    padding: 8,
  },
  generoPill: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 16,
    borderWidth: 1.5,
    backgroundColor: "transparent",
  },
  generoText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 11,
    letterSpacing: 1,
  },
  cacheRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 4,
  },
  cacheHalf: {
    flex: 1,
  },
  estruturaCard: {
    backgroundColor: DS.bgCard,
    borderRadius: 12,
    padding: 16,
    marginTop: 20,
    borderWidth: 1,
    borderColor: DS.bgSurface,
  },
  estruturaCardError: {
    borderColor: DS.danger,
  },
  estruturaHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  estruturaTitulo: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 14,
    color: DS.white,
  },
  estruturaSub: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textSec,
    marginTop: 2,
  },
  equipamentosContainer: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: DS.bgSurface,
  },
  equipamentosLabel: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 11,
    color: DS.textSec,
    letterSpacing: 2,
    marginBottom: 12,
  },
  checkGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  checkItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    width: "46%",
    paddingVertical: 6,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 5,
    borderWidth: 1.5,
    borderColor: DS.textDis,
    backgroundColor: DS.bgInput,
    justifyContent: "center",
    alignItems: "center",
  },
  checkboxOn: {
    borderColor: DS.accent,
    backgroundColor: DS.accent,
  },
  checkLabel: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.white,
    flexShrink: 1,
  },
  btnPrimary: {
    backgroundColor: DS.accent,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 28,
  },
  btnPrimaryText: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 13,
    color: DS.white,
    letterSpacing: 2,
  },
  btnBack: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginTop: 16,
    paddingVertical: 10,
  },
  btnBackText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 13,
    color: DS.textSec,
  },
});
