import { StyleSheet } from "react-native";
import { DS } from "./constants";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: DS.bg },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 52,
    paddingBottom: 16,
  },
  headerTitleWrap: { flex: 1, marginLeft: 12 },
  title: {
    fontFamily: "Montserrat-Bold",
    fontSize: 18,
    color: DS.textPrimary,
  },
  closedBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginHorizontal: 20,
    marginBottom: 12,
    padding: 12,
    backgroundColor: "rgba(245,158,11,0.12)",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(245,158,11,0.35)",
  },
  closedBannerText: {
    flex: 1,
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textSecondary,
    lineHeight: 18,
  },
  tabs: {
    flexDirection: "row",
    paddingHorizontal: 20,
    gap: 8,
    marginBottom: 16,
  },
  tabBtn: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: DS.border,
  },
  tabBtnOn: {
    backgroundColor: DS.accent,
    borderColor: DS.accent,
  },
  tabText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 12,
    color: DS.textSecondary,
  },
  tabTextOn: {
    color: DS.textPrimary,
  },
  list: { paddingHorizontal: 20, paddingBottom: 40 },
  loading: { flex: 1, justifyContent: "center", alignItems: "center" },
  card: {
    backgroundColor: DS.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: DS.border,
    padding: 16,
    marginBottom: 12,
  },
  cardTop: { flexDirection: "row", alignItems: "center" },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: DS.surface,
    justifyContent: "center",
    alignItems: "center",
  },
  cardBody: { flex: 1, marginLeft: 12 },
  name: {
    fontFamily: "Montserrat-Bold",
    fontSize: 15,
    color: DS.textPrimary,
    marginBottom: 4,
  },
  badgesRow: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginBottom: 4 },
  genreBadge: {
    backgroundColor: "rgba(123,97,255,0.2)",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
  },
  genreBadgeText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 9,
    color: DS.accent,
    letterSpacing: 1,
  },
  statusBadge: {
    backgroundColor: "rgba(0,206,201,0.15)",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
  },
  statusBadgeMuted: { backgroundColor: "rgba(136,136,170,0.15)" },
  statusBadgeRejected: {
    backgroundColor: "rgba(239,68,68,0.18)",
    borderWidth: 1,
    borderColor: "rgba(239,68,68,0.35)",
  },
  statusBadgeAccepted: {
    backgroundColor: "rgba(0,200,83,0.15)",
    borderWidth: 1,
    borderColor: "rgba(0,200,83,0.35)",
  },
  statusBadgeText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 9,
    color: DS.cyan,
    letterSpacing: 0.5,
  },
  statusBadgeTextRejected: { color: DS.danger },
  statusBadgeTextAccepted: { color: DS.success },
  meta: { flexDirection: "row", alignItems: "center", gap: 4 },
  rating: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 12,
    color: "#F39C12",
  },
  metaText: {
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    color: DS.textSecondary,
  },
  message: {
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: DS.textSecondary,
    marginTop: 10,
    lineHeight: 20,
    borderTopWidth: 1,
    borderTopColor: DS.border,
    paddingTop: 10,
  },
  valorLine: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 13,
    color: DS.cyan,
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: DS.border,
  },
  actions: { flexDirection: "row", gap: 10, marginTop: 12 },
  viewBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: DS.accent,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
  },
  viewBtnText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 12,
    color: DS.accent,
  },
  acceptBtn: {
    flex: 1,
    backgroundColor: DS.accent,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
  },
  acceptBtnText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 12,
    color: DS.textPrimary,
  },
  reacceptBtn: {
    flex: 1,
    backgroundColor: DS.danger,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  reacceptBtnText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 9,
    color: DS.textPrimary,
    textAlign: "center",
    letterSpacing: 0.3,
    lineHeight: 14,
  },
  contractBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: DS.success,
    borderRadius: 10,
    paddingVertical: 10,
    backgroundColor: "rgba(0,200,83,0.1)",
  },
  contractBtnText: {
    fontFamily: "Montserrat-Bold",
    fontSize: 11,
    color: DS.success,
  },
  empty: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: DS.textSecondary,
    textAlign: "center",
    paddingTop: 40,
  },
});
