import { StyleSheet } from "react-native";
import { DS } from "./constants";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: DS.bg },
  scrollContent: {
    paddingTop: 60,
    paddingHorizontal: 24,
    alignItems: "center",
  },
  successCircle: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: "rgba(0,200,150,0.12)",
    borderWidth: 2,
    borderColor: DS.success,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  successTitle: {
    fontFamily: "AkiraExpanded-Superbold",
    fontSize: 22,
    color: DS.white,
    textAlign: "center",
    marginBottom: 8,
  },
  successSubtitle: {
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    color: DS.textSec,
    textAlign: "center",
    marginBottom: 28,
    lineHeight: 22,
  },
  showCard: {
    width: "100%",
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(167,139,250,0.2)",
    overflow: "hidden",
    marginBottom: 24,
  },
  showCardImagePlaceholder: {
    height: 140,
    backgroundColor: "#2D1B4E",
    alignItems: "center",
    justifyContent: "center",
  },
  infoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    padding: 16,
    gap: 12,
  },
  infoCell: {
    width: "44%",
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 10,
    padding: 10,
  },
  infoCellLabel: {
    fontFamily: "Montserrat-Bold",
    fontSize: 9,
    color: DS.textDis,
    letterSpacing: 1,
    marginBottom: 2,
  },
  infoCellValue: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 12,
    color: DS.white,
    lineHeight: 17,
  },
  pixNotice: {
    width: "100%",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    backgroundColor: "rgba(243,156,18,0.1)",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(243,156,18,0.35)",
    padding: 16,
    marginBottom: 20,
  },
  pixNoticeText: {
    flex: 1,
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    color: "#E8D5A3",
    lineHeight: 20,
  },
  backLink: { paddingVertical: 8 },
  backLinkText: {
    fontFamily: "Montserrat-SemiBold",
    fontSize: 13,
    color: DS.textDis,
    letterSpacing: 1,
    textDecorationLine: "underline",
  },
  scrollBottomSpacer: { height: 32 },
});
