name: Toca Aqui CI/CD Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: echo "Rodando testes..."

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy to staging
        run: echo "Deploy para staging..."
