import { StyleSheet } from "react-native";
import { DS } from "./constants";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: DS.bg,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  title: {
    color: DS.text,
    fontFamily: "Montserrat-Bold",
    fontSize: 20,
  },
  subtitle: {
    color: DS.muted,
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    marginBottom: 24,
  },
  addBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: DS.addBtnBg,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
  },
  addBtnText: {
    color: DS.accent,
    fontFamily: "Montserrat-SemiBold",
    fontSize: 13,
  },
  list: { paddingBottom: 40 },
  card: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: DS.card,
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: DS.border,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: DS.avatarBg,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  avatarText: {
    color: DS.accent,
    fontFamily: "Montserrat-Bold",
    fontSize: 18,
  },
  info: { flex: 1 },
  name: {
    color: DS.text,
    fontFamily: "Montserrat-SemiBold",
    fontSize: 14,
  },
  email: {
    color: DS.muted,
    fontFamily: "Montserrat-Regular",
    fontSize: 12,
    marginTop: 2,
  },
  rightCol: { alignItems: "flex-end", gap: 6 },
  badge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  badgeOwner: { backgroundColor: DS.ownerBadgeBg },
  badgeAdmin: { backgroundColor: DS.adminBadgeBg },
  badgeText: {
    color: DS.text,
    fontFamily: "Montserrat-SemiBold",
    fontSize: 11,
  },
  removeBtn: { padding: 4 },
  empty: {
    color: DS.muted,
    textAlign: "center",
    marginTop: 40,
    fontFamily: "Montserrat-Regular",
  },
  loading: { marginTop: 40 },
  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0,0,0,0.6)",
  },
  modalBox: {
    backgroundColor: DS.card,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 40,
  },
  modalTitle: {
    color: DS.text,
    fontFamily: "Montserrat-Bold",
    fontSize: 18,
    marginBottom: 6,
  },
  modalSub: {
    color: DS.muted,
    fontFamily: "Montserrat-Regular",
    fontSize: 13,
    marginBottom: 20,
  },
  input: {
    backgroundColor: DS.bg,
    borderWidth: 1,
    borderColor: DS.border,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: DS.text,
    fontFamily: "Montserrat-Regular",
    fontSize: 14,
    marginBottom: 4,
  },
  inputError: { borderColor: DS.danger },
  modalActions: { flexDirection: "row", gap: 12 },
  cancelBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: DS.border,
    alignItems: "center",
  },
  cancelText: {
    color: DS.muted,
    fontFamily: "Montserrat-SemiBold",
  },
  confirmBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 10,
    backgroundColor: DS.accent,
    alignItems: "center",
  },
  confirmText: {
    color: "#fff",
    fontFamily: "Montserrat-SemiBold",
  },
  disabled: { opacity: 0.5 },
});
